package com.nomad.data.agent.domain.dao.common;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table aip_algorithm
 *
 * @mbg.generated do_not_delete_during_merge Thu Oct 17 13:20:23 KST 2019
 */
public class AipAlgorithmKey {
    /**
     * 알고리즘아이디
     */
    private String athmId;

    /**
     * 알고리즘아이디
     */
    public String getAthmId() {
        return athmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.ATHM_ID
     *
     * @param athmId the value for aip_algorithm.ATHM_ID
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setAthmId(String athmId) {
        this.athmId = athmId == null ? null : athmId.trim();
    }
}