package com.nomad.data.agent.domain.dao.common;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table aip_algorithm
 *
 * @mbg.generated do_not_delete_during_merge Thu Oct 17 13:20:23 KST 2019
 */
public class AipAlgorithm extends AipAlgorithmKey {
    /**
     * 알고리즘이름
     */
    private String athmNm;

    /**
     * 알고리즘설명
     */
    private String athmDesc;

    /**
     * 저장소이름
     */
    private String rptrNm;

    /**
     * 라이브러리종류
     */
    private String libTp;

    /**
     * 알고리즘종류
     */
    private String athmTp;

    /**
     * 소유자아이디
     */
    private String ownerId;

    /**
     * 공개여부
     */
    private String pubFl;

    /**
     * 등록일
     */
    private Date regDt;

    /**
     * 수정일
     */
    private Date modDt;

    /**
     * 알고리즘이름
     */
    public String getAthmNm() {
        return athmNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.ATHM_NM
     *
     * @param athmNm the value for aip_algorithm.ATHM_NM
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setAthmNm(String athmNm) {
        this.athmNm = athmNm == null ? null : athmNm.trim();
    }

    /**
     * 알고리즘설명
     */
    public String getAthmDesc() {
        return athmDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.ATHM_DESC
     *
     * @param athmDesc the value for aip_algorithm.ATHM_DESC
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setAthmDesc(String athmDesc) {
        this.athmDesc = athmDesc == null ? null : athmDesc.trim();
    }

    /**
     * 저장소이름
     */
    public String getRptrNm() {
        return rptrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.RPTR_NM
     *
     * @param rptrNm the value for aip_algorithm.RPTR_NM
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setRptrNm(String rptrNm) {
        this.rptrNm = rptrNm == null ? null : rptrNm.trim();
    }

    /**
     * 라이브러리종류
     */
    public String getLibTp() {
        return libTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.LIB_TP
     *
     * @param libTp the value for aip_algorithm.LIB_TP
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setLibTp(String libTp) {
        this.libTp = libTp == null ? null : libTp.trim();
    }

    /**
     * 알고리즘종류
     */
    public String getAthmTp() {
        return athmTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.ATHM_TP
     *
     * @param athmTp the value for aip_algorithm.ATHM_TP
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setAthmTp(String athmTp) {
        this.athmTp = athmTp == null ? null : athmTp.trim();
    }

    /**
     * 소유자아이디
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.OWNER_ID
     *
     * @param ownerId the value for aip_algorithm.OWNER_ID
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * 공개여부
     */
    public String getPubFl() {
        return pubFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.PUB_FL
     *
     * @param pubFl the value for aip_algorithm.PUB_FL
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setPubFl(String pubFl) {
        this.pubFl = pubFl == null ? null : pubFl.trim();
    }

    /**
     * 등록일
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.REG_DT
     *
     * @param regDt the value for aip_algorithm.REG_DT
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * 수정일
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_algorithm.MOD_DT
     *
     * @param modDt the value for aip_algorithm.MOD_DT
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }

}