package com.nomad.data.agent.domain.dao.common;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AipDataSetFileMapExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public AipDataSetFileMapExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDataFileMapIdIsNull() {
            addCriterion("DATA_FILE_MAP_ID is null");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdIsNotNull() {
            addCriterion("DATA_FILE_MAP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdEqualTo(String value) {
            addCriterion("DATA_FILE_MAP_ID =", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdNotEqualTo(String value) {
            addCriterion("DATA_FILE_MAP_ID <>", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdGreaterThan(String value) {
            addCriterion("DATA_FILE_MAP_ID >", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_FILE_MAP_ID >=", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdLessThan(String value) {
            addCriterion("DATA_FILE_MAP_ID <", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdLessThanOrEqualTo(String value) {
            addCriterion("DATA_FILE_MAP_ID <=", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdLike(String value) {
            addCriterion("DATA_FILE_MAP_ID like", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdNotLike(String value) {
            addCriterion("DATA_FILE_MAP_ID not like", value, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdIn(List<String> values) {
            addCriterion("DATA_FILE_MAP_ID in", values, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdNotIn(List<String> values) {
            addCriterion("DATA_FILE_MAP_ID not in", values, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdBetween(String value1, String value2) {
            addCriterion("DATA_FILE_MAP_ID between", value1, value2, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataFileMapIdNotBetween(String value1, String value2) {
            addCriterion("DATA_FILE_MAP_ID not between", value1, value2, "dataFileMapId");
            return (Criteria) this;
        }

        public Criteria andDataIdIsNull() {
            addCriterion("DATA_ID is null");
            return (Criteria) this;
        }

        public Criteria andDataIdIsNotNull() {
            addCriterion("DATA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDataIdEqualTo(String value) {
            addCriterion("DATA_ID =", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotEqualTo(String value) {
            addCriterion("DATA_ID <>", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdGreaterThan(String value) {
            addCriterion("DATA_ID >", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_ID >=", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdLessThan(String value) {
            addCriterion("DATA_ID <", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdLessThanOrEqualTo(String value) {
            addCriterion("DATA_ID <=", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdLike(String value) {
            addCriterion("DATA_ID like", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotLike(String value) {
            addCriterion("DATA_ID not like", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdIn(List<String> values) {
            addCriterion("DATA_ID in", values, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotIn(List<String> values) {
            addCriterion("DATA_ID not in", values, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdBetween(String value1, String value2) {
            addCriterion("DATA_ID between", value1, value2, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotBetween(String value1, String value2) {
            addCriterion("DATA_ID not between", value1, value2, "dataId");
            return (Criteria) this;
        }

        public Criteria andFileNmIsNull() {
            addCriterion("FILE_NM is null");
            return (Criteria) this;
        }

        public Criteria andFileNmIsNotNull() {
            addCriterion("FILE_NM is not null");
            return (Criteria) this;
        }

        public Criteria andFileNmEqualTo(String value) {
            addCriterion("FILE_NM =", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotEqualTo(String value) {
            addCriterion("FILE_NM <>", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmGreaterThan(String value) {
            addCriterion("FILE_NM >", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_NM >=", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmLessThan(String value) {
            addCriterion("FILE_NM <", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmLessThanOrEqualTo(String value) {
            addCriterion("FILE_NM <=", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmLike(String value) {
            addCriterion("FILE_NM like", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotLike(String value) {
            addCriterion("FILE_NM not like", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmIn(List<String> values) {
            addCriterion("FILE_NM in", values, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotIn(List<String> values) {
            addCriterion("FILE_NM not in", values, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmBetween(String value1, String value2) {
            addCriterion("FILE_NM between", value1, value2, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotBetween(String value1, String value2) {
            addCriterion("FILE_NM not between", value1, value2, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("FILE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("FILE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("FILE_PATH =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("FILE_PATH <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("FILE_PATH >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_PATH >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("FILE_PATH <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("FILE_PATH <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("FILE_PATH like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("FILE_PATH not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("FILE_PATH in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("FILE_PATH not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("FILE_PATH between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("FILE_PATH not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFileSzIsNull() {
            addCriterion("FILE_SZ is null");
            return (Criteria) this;
        }

        public Criteria andFileSzIsNotNull() {
            addCriterion("FILE_SZ is not null");
            return (Criteria) this;
        }

        public Criteria andFileSzEqualTo(Long value) {
            addCriterion("FILE_SZ =", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzNotEqualTo(Long value) {
            addCriterion("FILE_SZ <>", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzGreaterThan(Long value) {
            addCriterion("FILE_SZ >", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzGreaterThanOrEqualTo(Long value) {
            addCriterion("FILE_SZ >=", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzLessThan(Long value) {
            addCriterion("FILE_SZ <", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzLessThanOrEqualTo(Long value) {
            addCriterion("FILE_SZ <=", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzIn(List<Long> values) {
            addCriterion("FILE_SZ in", values, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzNotIn(List<Long> values) {
            addCriterion("FILE_SZ not in", values, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzBetween(Long value1, Long value2) {
            addCriterion("FILE_SZ between", value1, value2, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzNotBetween(Long value1, Long value2) {
            addCriterion("FILE_SZ not between", value1, value2, "fileSz");
            return (Criteria) this;
        }

        public Criteria andDataCntIsNull() {
            addCriterion("DATA_CNT is null");
            return (Criteria) this;
        }

        public Criteria andDataCntIsNotNull() {
            addCriterion("DATA_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andDataCntEqualTo(Long value) {
            addCriterion("DATA_CNT =", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntNotEqualTo(Long value) {
            addCriterion("DATA_CNT <>", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntGreaterThan(Long value) {
            addCriterion("DATA_CNT >", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntGreaterThanOrEqualTo(Long value) {
            addCriterion("DATA_CNT >=", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntLessThan(Long value) {
            addCriterion("DATA_CNT <", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntLessThanOrEqualTo(Long value) {
            addCriterion("DATA_CNT <=", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntIn(List<Long> values) {
            addCriterion("DATA_CNT in", values, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntNotIn(List<Long> values) {
            addCriterion("DATA_CNT not in", values, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntBetween(Long value1, Long value2) {
            addCriterion("DATA_CNT between", value1, value2, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntNotBetween(Long value1, Long value2) {
            addCriterion("DATA_CNT not between", value1, value2, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNull() {
            addCriterion("REG_DT is null");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNotNull() {
            addCriterion("REG_DT is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtEqualTo(Date value) {
            addCriterion("REG_DT =", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotEqualTo(Date value) {
            addCriterion("REG_DT <>", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThan(Date value) {
            addCriterion("REG_DT >", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DT >=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThan(Date value) {
            addCriterion("REG_DT <", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThanOrEqualTo(Date value) {
            addCriterion("REG_DT <=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtIn(List<Date> values) {
            addCriterion("REG_DT in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotIn(List<Date> values) {
            addCriterion("REG_DT not in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtBetween(Date value1, Date value2) {
            addCriterion("REG_DT between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotBetween(Date value1, Date value2) {
            addCriterion("REG_DT not between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andModDtIsNull() {
            addCriterion("MOD_DT is null");
            return (Criteria) this;
        }

        public Criteria andModDtIsNotNull() {
            addCriterion("MOD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andModDtEqualTo(Date value) {
            addCriterion("MOD_DT =", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotEqualTo(Date value) {
            addCriterion("MOD_DT <>", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThan(Date value) {
            addCriterion("MOD_DT >", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DT >=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThan(Date value) {
            addCriterion("MOD_DT <", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DT <=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtIn(List<Date> values) {
            addCriterion("MOD_DT in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotIn(List<Date> values) {
            addCriterion("MOD_DT not in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtBetween(Date value1, Date value2) {
            addCriterion("MOD_DT between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DT not between", value1, value2, "modDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 29 17:19:36 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}