package com.nomad.data.agent.domain.dao.common;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AipDockerImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public AipDockerImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImgIdIsNull() {
            addCriterion("IMG_ID is null");
            return (Criteria) this;
        }

        public Criteria andImgIdIsNotNull() {
            addCriterion("IMG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andImgIdEqualTo(String value) {
            addCriterion("IMG_ID =", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotEqualTo(String value) {
            addCriterion("IMG_ID <>", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdGreaterThan(String value) {
            addCriterion("IMG_ID >", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdGreaterThanOrEqualTo(String value) {
            addCriterion("IMG_ID >=", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLessThan(String value) {
            addCriterion("IMG_ID <", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLessThanOrEqualTo(String value) {
            addCriterion("IMG_ID <=", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLike(String value) {
            addCriterion("IMG_ID like", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotLike(String value) {
            addCriterion("IMG_ID not like", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdIn(List<String> values) {
            addCriterion("IMG_ID in", values, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotIn(List<String> values) {
            addCriterion("IMG_ID not in", values, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdBetween(String value1, String value2) {
            addCriterion("IMG_ID between", value1, value2, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotBetween(String value1, String value2) {
            addCriterion("IMG_ID not between", value1, value2, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgTpIsNull() {
            addCriterion("IMG_TP is null");
            return (Criteria) this;
        }

        public Criteria andImgTpIsNotNull() {
            addCriterion("IMG_TP is not null");
            return (Criteria) this;
        }

        public Criteria andImgTpEqualTo(String value) {
            addCriterion("IMG_TP =", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpNotEqualTo(String value) {
            addCriterion("IMG_TP <>", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpGreaterThan(String value) {
            addCriterion("IMG_TP >", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpGreaterThanOrEqualTo(String value) {
            addCriterion("IMG_TP >=", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpLessThan(String value) {
            addCriterion("IMG_TP <", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpLessThanOrEqualTo(String value) {
            addCriterion("IMG_TP <=", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpLike(String value) {
            addCriterion("IMG_TP like", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpNotLike(String value) {
            addCriterion("IMG_TP not like", value, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpIn(List<String> values) {
            addCriterion("IMG_TP in", values, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpNotIn(List<String> values) {
            addCriterion("IMG_TP not in", values, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpBetween(String value1, String value2) {
            addCriterion("IMG_TP between", value1, value2, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgTpNotBetween(String value1, String value2) {
            addCriterion("IMG_TP not between", value1, value2, "imgTp");
            return (Criteria) this;
        }

        public Criteria andImgNmIsNull() {
            addCriterion("IMG_NM is null");
            return (Criteria) this;
        }

        public Criteria andImgNmIsNotNull() {
            addCriterion("IMG_NM is not null");
            return (Criteria) this;
        }

        public Criteria andImgNmEqualTo(String value) {
            addCriterion("IMG_NM =", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmNotEqualTo(String value) {
            addCriterion("IMG_NM <>", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmGreaterThan(String value) {
            addCriterion("IMG_NM >", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmGreaterThanOrEqualTo(String value) {
            addCriterion("IMG_NM >=", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmLessThan(String value) {
            addCriterion("IMG_NM <", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmLessThanOrEqualTo(String value) {
            addCriterion("IMG_NM <=", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmLike(String value) {
            addCriterion("IMG_NM like", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmNotLike(String value) {
            addCriterion("IMG_NM not like", value, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmIn(List<String> values) {
            addCriterion("IMG_NM in", values, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmNotIn(List<String> values) {
            addCriterion("IMG_NM not in", values, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmBetween(String value1, String value2) {
            addCriterion("IMG_NM between", value1, value2, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgNmNotBetween(String value1, String value2) {
            addCriterion("IMG_NM not between", value1, value2, "imgNm");
            return (Criteria) this;
        }

        public Criteria andImgDescIsNull() {
            addCriterion("IMG_DESC is null");
            return (Criteria) this;
        }

        public Criteria andImgDescIsNotNull() {
            addCriterion("IMG_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andImgDescEqualTo(String value) {
            addCriterion("IMG_DESC =", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescNotEqualTo(String value) {
            addCriterion("IMG_DESC <>", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescGreaterThan(String value) {
            addCriterion("IMG_DESC >", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescGreaterThanOrEqualTo(String value) {
            addCriterion("IMG_DESC >=", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescLessThan(String value) {
            addCriterion("IMG_DESC <", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescLessThanOrEqualTo(String value) {
            addCriterion("IMG_DESC <=", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescLike(String value) {
            addCriterion("IMG_DESC like", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescNotLike(String value) {
            addCriterion("IMG_DESC not like", value, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescIn(List<String> values) {
            addCriterion("IMG_DESC in", values, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescNotIn(List<String> values) {
            addCriterion("IMG_DESC not in", values, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescBetween(String value1, String value2) {
            addCriterion("IMG_DESC between", value1, value2, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andImgDescNotBetween(String value1, String value2) {
            addCriterion("IMG_DESC not between", value1, value2, "imgDesc");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagIsNull() {
            addCriterion("DCKR_IMG_TAG is null");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagIsNotNull() {
            addCriterion("DCKR_IMG_TAG is not null");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagEqualTo(String value) {
            addCriterion("DCKR_IMG_TAG =", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagNotEqualTo(String value) {
            addCriterion("DCKR_IMG_TAG <>", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagGreaterThan(String value) {
            addCriterion("DCKR_IMG_TAG >", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagGreaterThanOrEqualTo(String value) {
            addCriterion("DCKR_IMG_TAG >=", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagLessThan(String value) {
            addCriterion("DCKR_IMG_TAG <", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagLessThanOrEqualTo(String value) {
            addCriterion("DCKR_IMG_TAG <=", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagLike(String value) {
            addCriterion("DCKR_IMG_TAG like", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagNotLike(String value) {
            addCriterion("DCKR_IMG_TAG not like", value, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagIn(List<String> values) {
            addCriterion("DCKR_IMG_TAG in", values, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagNotIn(List<String> values) {
            addCriterion("DCKR_IMG_TAG not in", values, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagBetween(String value1, String value2) {
            addCriterion("DCKR_IMG_TAG between", value1, value2, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgTagNotBetween(String value1, String value2) {
            addCriterion("DCKR_IMG_TAG not between", value1, value2, "dckrImgTag");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmIsNull() {
            addCriterion("DCKR_IMG_NM is null");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmIsNotNull() {
            addCriterion("DCKR_IMG_NM is not null");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmEqualTo(String value) {
            addCriterion("DCKR_IMG_NM =", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmNotEqualTo(String value) {
            addCriterion("DCKR_IMG_NM <>", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmGreaterThan(String value) {
            addCriterion("DCKR_IMG_NM >", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmGreaterThanOrEqualTo(String value) {
            addCriterion("DCKR_IMG_NM >=", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmLessThan(String value) {
            addCriterion("DCKR_IMG_NM <", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmLessThanOrEqualTo(String value) {
            addCriterion("DCKR_IMG_NM <=", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmLike(String value) {
            addCriterion("DCKR_IMG_NM like", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmNotLike(String value) {
            addCriterion("DCKR_IMG_NM not like", value, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmIn(List<String> values) {
            addCriterion("DCKR_IMG_NM in", values, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmNotIn(List<String> values) {
            addCriterion("DCKR_IMG_NM not in", values, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmBetween(String value1, String value2) {
            addCriterion("DCKR_IMG_NM between", value1, value2, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andDckrImgNmNotBetween(String value1, String value2) {
            addCriterion("DCKR_IMG_NM not between", value1, value2, "dckrImgNm");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNull() {
            addCriterion("REG_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNotNull() {
            addCriterion("REG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegIdEqualTo(String value) {
            addCriterion("REG_ID =", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotEqualTo(String value) {
            addCriterion("REG_ID <>", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThan(String value) {
            addCriterion("REG_ID >", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThanOrEqualTo(String value) {
            addCriterion("REG_ID >=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThan(String value) {
            addCriterion("REG_ID <", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThanOrEqualTo(String value) {
            addCriterion("REG_ID <=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLike(String value) {
            addCriterion("REG_ID like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotLike(String value) {
            addCriterion("REG_ID not like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdIn(List<String> values) {
            addCriterion("REG_ID in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotIn(List<String> values) {
            addCriterion("REG_ID not in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdBetween(String value1, String value2) {
            addCriterion("REG_ID between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotBetween(String value1, String value2) {
            addCriterion("REG_ID not between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andDelFlIsNull() {
            addCriterion("DEL_FL is null");
            return (Criteria) this;
        }

        public Criteria andDelFlIsNotNull() {
            addCriterion("DEL_FL is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlEqualTo(String value) {
            addCriterion("DEL_FL =", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotEqualTo(String value) {
            addCriterion("DEL_FL <>", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlGreaterThan(String value) {
            addCriterion("DEL_FL >", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_FL >=", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLessThan(String value) {
            addCriterion("DEL_FL <", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLessThanOrEqualTo(String value) {
            addCriterion("DEL_FL <=", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLike(String value) {
            addCriterion("DEL_FL like", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotLike(String value) {
            addCriterion("DEL_FL not like", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlIn(List<String> values) {
            addCriterion("DEL_FL in", values, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotIn(List<String> values) {
            addCriterion("DEL_FL not in", values, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlBetween(String value1, String value2) {
            addCriterion("DEL_FL between", value1, value2, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotBetween(String value1, String value2) {
            addCriterion("DEL_FL not between", value1, value2, "delFl");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNull() {
            addCriterion("REG_DT is null");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNotNull() {
            addCriterion("REG_DT is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtEqualTo(Date value) {
            addCriterion("REG_DT =", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotEqualTo(Date value) {
            addCriterion("REG_DT <>", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThan(Date value) {
            addCriterion("REG_DT >", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DT >=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThan(Date value) {
            addCriterion("REG_DT <", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThanOrEqualTo(Date value) {
            addCriterion("REG_DT <=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtIn(List<Date> values) {
            addCriterion("REG_DT in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotIn(List<Date> values) {
            addCriterion("REG_DT not in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtBetween(Date value1, Date value2) {
            addCriterion("REG_DT between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotBetween(Date value1, Date value2) {
            addCriterion("REG_DT not between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andModDtIsNull() {
            addCriterion("MOD_DT is null");
            return (Criteria) this;
        }

        public Criteria andModDtIsNotNull() {
            addCriterion("MOD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andModDtEqualTo(Date value) {
            addCriterion("MOD_DT =", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotEqualTo(Date value) {
            addCriterion("MOD_DT <>", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThan(Date value) {
            addCriterion("MOD_DT >", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DT >=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThan(Date value) {
            addCriterion("MOD_DT <", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DT <=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtIn(List<Date> values) {
            addCriterion("MOD_DT in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotIn(List<Date> values) {
            addCriterion("MOD_DT not in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtBetween(Date value1, Date value2) {
            addCriterion("MOD_DT between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DT not between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andAdvOptIsNull() {
            addCriterion("ADV_OPT is null");
            return (Criteria) this;
        }

        public Criteria andAdvOptIsNotNull() {
            addCriterion("ADV_OPT is not null");
            return (Criteria) this;
        }

        public Criteria andAdvOptEqualTo(String value) {
            addCriterion("ADV_OPT =", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptNotEqualTo(String value) {
            addCriterion("ADV_OPT <>", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptGreaterThan(String value) {
            addCriterion("ADV_OPT >", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptGreaterThanOrEqualTo(String value) {
            addCriterion("ADV_OPT >=", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptLessThan(String value) {
            addCriterion("ADV_OPT <", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptLessThanOrEqualTo(String value) {
            addCriterion("ADV_OPT <=", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptLike(String value) {
            addCriterion("ADV_OPT like", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptNotLike(String value) {
            addCriterion("ADV_OPT not like", value, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptIn(List<String> values) {
            addCriterion("ADV_OPT in", values, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptNotIn(List<String> values) {
            addCriterion("ADV_OPT not in", values, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptBetween(String value1, String value2) {
            addCriterion("ADV_OPT between", value1, value2, "advOpt");
            return (Criteria) this;
        }

        public Criteria andAdvOptNotBetween(String value1, String value2) {
            addCriterion("ADV_OPT not between", value1, value2, "advOpt");
            return (Criteria) this;
        }

        public Criteria andProcTpIsNull() {
            addCriterion("PROC_TP is null");
            return (Criteria) this;
        }

        public Criteria andProcTpIsNotNull() {
            addCriterion("PROC_TP is not null");
            return (Criteria) this;
        }

        public Criteria andProcTpEqualTo(String value) {
            addCriterion("PROC_TP =", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpNotEqualTo(String value) {
            addCriterion("PROC_TP <>", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpGreaterThan(String value) {
            addCriterion("PROC_TP >", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpGreaterThanOrEqualTo(String value) {
            addCriterion("PROC_TP >=", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpLessThan(String value) {
            addCriterion("PROC_TP <", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpLessThanOrEqualTo(String value) {
            addCriterion("PROC_TP <=", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpLike(String value) {
            addCriterion("PROC_TP like", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpNotLike(String value) {
            addCriterion("PROC_TP not like", value, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpIn(List<String> values) {
            addCriterion("PROC_TP in", values, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpNotIn(List<String> values) {
            addCriterion("PROC_TP not in", values, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpBetween(String value1, String value2) {
            addCriterion("PROC_TP between", value1, value2, "procTp");
            return (Criteria) this;
        }

        public Criteria andProcTpNotBetween(String value1, String value2) {
            addCriterion("PROC_TP not between", value1, value2, "procTp");
            return (Criteria) this;
        }

        public Criteria andImgPortIsNull() {
            addCriterion("IMG_PORT is null");
            return (Criteria) this;
        }

        public Criteria andImgPortIsNotNull() {
            addCriterion("IMG_PORT is not null");
            return (Criteria) this;
        }

        public Criteria andImgPortEqualTo(BigDecimal value) {
            addCriterion("IMG_PORT =", value, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortNotEqualTo(BigDecimal value) {
            addCriterion("IMG_PORT <>", value, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortGreaterThan(BigDecimal value) {
            addCriterion("IMG_PORT >", value, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IMG_PORT >=", value, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortLessThan(BigDecimal value) {
            addCriterion("IMG_PORT <", value, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IMG_PORT <=", value, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortIn(List<BigDecimal> values) {
            addCriterion("IMG_PORT in", values, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortNotIn(List<BigDecimal> values) {
            addCriterion("IMG_PORT not in", values, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMG_PORT between", value1, value2, "imgPort");
            return (Criteria) this;
        }

        public Criteria andImgPortNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMG_PORT not between", value1, value2, "imgPort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 22 17:39:33 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}