package com.nomad.data.agent.domain.dao.common;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AipDataSourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public AipDataSourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDsIdIsNull() {
            addCriterion("DS_ID is null");
            return (Criteria) this;
        }

        public Criteria andDsIdIsNotNull() {
            addCriterion("DS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDsIdEqualTo(String value) {
            addCriterion("DS_ID =", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotEqualTo(String value) {
            addCriterion("DS_ID <>", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdGreaterThan(String value) {
            addCriterion("DS_ID >", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdGreaterThanOrEqualTo(String value) {
            addCriterion("DS_ID >=", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLessThan(String value) {
            addCriterion("DS_ID <", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLessThanOrEqualTo(String value) {
            addCriterion("DS_ID <=", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLike(String value) {
            addCriterion("DS_ID like", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotLike(String value) {
            addCriterion("DS_ID not like", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdIn(List<String> values) {
            addCriterion("DS_ID in", values, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotIn(List<String> values) {
            addCriterion("DS_ID not in", values, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdBetween(String value1, String value2) {
            addCriterion("DS_ID between", value1, value2, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotBetween(String value1, String value2) {
            addCriterion("DS_ID not between", value1, value2, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsNmIsNull() {
            addCriterion("DS_NM is null");
            return (Criteria) this;
        }

        public Criteria andDsNmIsNotNull() {
            addCriterion("DS_NM is not null");
            return (Criteria) this;
        }

        public Criteria andDsNmEqualTo(String value) {
            addCriterion("DS_NM =", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmNotEqualTo(String value) {
            addCriterion("DS_NM <>", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmGreaterThan(String value) {
            addCriterion("DS_NM >", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmGreaterThanOrEqualTo(String value) {
            addCriterion("DS_NM >=", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmLessThan(String value) {
            addCriterion("DS_NM <", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmLessThanOrEqualTo(String value) {
            addCriterion("DS_NM <=", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmLike(String value) {
            addCriterion("DS_NM like", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmNotLike(String value) {
            addCriterion("DS_NM not like", value, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmIn(List<String> values) {
            addCriterion("DS_NM in", values, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmNotIn(List<String> values) {
            addCriterion("DS_NM not in", values, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmBetween(String value1, String value2) {
            addCriterion("DS_NM between", value1, value2, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsNmNotBetween(String value1, String value2) {
            addCriterion("DS_NM not between", value1, value2, "dsNm");
            return (Criteria) this;
        }

        public Criteria andDsTpIsNull() {
            addCriterion("DS_TP is null");
            return (Criteria) this;
        }

        public Criteria andDsTpIsNotNull() {
            addCriterion("DS_TP is not null");
            return (Criteria) this;
        }

        public Criteria andDsTpEqualTo(String value) {
            addCriterion("DS_TP =", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpNotEqualTo(String value) {
            addCriterion("DS_TP <>", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpGreaterThan(String value) {
            addCriterion("DS_TP >", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpGreaterThanOrEqualTo(String value) {
            addCriterion("DS_TP >=", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpLessThan(String value) {
            addCriterion("DS_TP <", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpLessThanOrEqualTo(String value) {
            addCriterion("DS_TP <=", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpLike(String value) {
            addCriterion("DS_TP like", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpNotLike(String value) {
            addCriterion("DS_TP not like", value, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpIn(List<String> values) {
            addCriterion("DS_TP in", values, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpNotIn(List<String> values) {
            addCriterion("DS_TP not in", values, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpBetween(String value1, String value2) {
            addCriterion("DS_TP between", value1, value2, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsTpNotBetween(String value1, String value2) {
            addCriterion("DS_TP not between", value1, value2, "dsTp");
            return (Criteria) this;
        }

        public Criteria andDsDescIsNull() {
            addCriterion("DS_DESC is null");
            return (Criteria) this;
        }

        public Criteria andDsDescIsNotNull() {
            addCriterion("DS_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andDsDescEqualTo(String value) {
            addCriterion("DS_DESC =", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescNotEqualTo(String value) {
            addCriterion("DS_DESC <>", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescGreaterThan(String value) {
            addCriterion("DS_DESC >", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescGreaterThanOrEqualTo(String value) {
            addCriterion("DS_DESC >=", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescLessThan(String value) {
            addCriterion("DS_DESC <", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescLessThanOrEqualTo(String value) {
            addCriterion("DS_DESC <=", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescLike(String value) {
            addCriterion("DS_DESC like", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescNotLike(String value) {
            addCriterion("DS_DESC not like", value, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescIn(List<String> values) {
            addCriterion("DS_DESC in", values, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescNotIn(List<String> values) {
            addCriterion("DS_DESC not in", values, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescBetween(String value1, String value2) {
            addCriterion("DS_DESC between", value1, value2, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsDescNotBetween(String value1, String value2) {
            addCriterion("DS_DESC not between", value1, value2, "dsDesc");
            return (Criteria) this;
        }

        public Criteria andDsConnIpIsNull() {
            addCriterion("DS_CONN_IP is null");
            return (Criteria) this;
        }

        public Criteria andDsConnIpIsNotNull() {
            addCriterion("DS_CONN_IP is not null");
            return (Criteria) this;
        }

        public Criteria andDsConnIpEqualTo(String value) {
            addCriterion("DS_CONN_IP =", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpNotEqualTo(String value) {
            addCriterion("DS_CONN_IP <>", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpGreaterThan(String value) {
            addCriterion("DS_CONN_IP >", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpGreaterThanOrEqualTo(String value) {
            addCriterion("DS_CONN_IP >=", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpLessThan(String value) {
            addCriterion("DS_CONN_IP <", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpLessThanOrEqualTo(String value) {
            addCriterion("DS_CONN_IP <=", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpLike(String value) {
            addCriterion("DS_CONN_IP like", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpNotLike(String value) {
            addCriterion("DS_CONN_IP not like", value, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpIn(List<String> values) {
            addCriterion("DS_CONN_IP in", values, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpNotIn(List<String> values) {
            addCriterion("DS_CONN_IP not in", values, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpBetween(String value1, String value2) {
            addCriterion("DS_CONN_IP between", value1, value2, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnIpNotBetween(String value1, String value2) {
            addCriterion("DS_CONN_IP not between", value1, value2, "dsConnIp");
            return (Criteria) this;
        }

        public Criteria andDsConnPortIsNull() {
            addCriterion("DS_CONN_PORT is null");
            return (Criteria) this;
        }

        public Criteria andDsConnPortIsNotNull() {
            addCriterion("DS_CONN_PORT is not null");
            return (Criteria) this;
        }

        public Criteria andDsConnPortEqualTo(String value) {
            addCriterion("DS_CONN_PORT =", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortNotEqualTo(String value) {
            addCriterion("DS_CONN_PORT <>", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortGreaterThan(String value) {
            addCriterion("DS_CONN_PORT >", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortGreaterThanOrEqualTo(String value) {
            addCriterion("DS_CONN_PORT >=", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortLessThan(String value) {
            addCriterion("DS_CONN_PORT <", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortLessThanOrEqualTo(String value) {
            addCriterion("DS_CONN_PORT <=", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortLike(String value) {
            addCriterion("DS_CONN_PORT like", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortNotLike(String value) {
            addCriterion("DS_CONN_PORT not like", value, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortIn(List<String> values) {
            addCriterion("DS_CONN_PORT in", values, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortNotIn(List<String> values) {
            addCriterion("DS_CONN_PORT not in", values, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortBetween(String value1, String value2) {
            addCriterion("DS_CONN_PORT between", value1, value2, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnPortNotBetween(String value1, String value2) {
            addCriterion("DS_CONN_PORT not between", value1, value2, "dsConnPort");
            return (Criteria) this;
        }

        public Criteria andDsConnIdIsNull() {
            addCriterion("DS_CONN_ID is null");
            return (Criteria) this;
        }

        public Criteria andDsConnIdIsNotNull() {
            addCriterion("DS_CONN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDsConnIdEqualTo(String value) {
            addCriterion("DS_CONN_ID =", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdNotEqualTo(String value) {
            addCriterion("DS_CONN_ID <>", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdGreaterThan(String value) {
            addCriterion("DS_CONN_ID >", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdGreaterThanOrEqualTo(String value) {
            addCriterion("DS_CONN_ID >=", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdLessThan(String value) {
            addCriterion("DS_CONN_ID <", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdLessThanOrEqualTo(String value) {
            addCriterion("DS_CONN_ID <=", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdLike(String value) {
            addCriterion("DS_CONN_ID like", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdNotLike(String value) {
            addCriterion("DS_CONN_ID not like", value, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdIn(List<String> values) {
            addCriterion("DS_CONN_ID in", values, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdNotIn(List<String> values) {
            addCriterion("DS_CONN_ID not in", values, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdBetween(String value1, String value2) {
            addCriterion("DS_CONN_ID between", value1, value2, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnIdNotBetween(String value1, String value2) {
            addCriterion("DS_CONN_ID not between", value1, value2, "dsConnId");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdIsNull() {
            addCriterion("DS_CONN_PSWD is null");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdIsNotNull() {
            addCriterion("DS_CONN_PSWD is not null");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdEqualTo(String value) {
            addCriterion("DS_CONN_PSWD =", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdNotEqualTo(String value) {
            addCriterion("DS_CONN_PSWD <>", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdGreaterThan(String value) {
            addCriterion("DS_CONN_PSWD >", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdGreaterThanOrEqualTo(String value) {
            addCriterion("DS_CONN_PSWD >=", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdLessThan(String value) {
            addCriterion("DS_CONN_PSWD <", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdLessThanOrEqualTo(String value) {
            addCriterion("DS_CONN_PSWD <=", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdLike(String value) {
            addCriterion("DS_CONN_PSWD like", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdNotLike(String value) {
            addCriterion("DS_CONN_PSWD not like", value, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdIn(List<String> values) {
            addCriterion("DS_CONN_PSWD in", values, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdNotIn(List<String> values) {
            addCriterion("DS_CONN_PSWD not in", values, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdBetween(String value1, String value2) {
            addCriterion("DS_CONN_PSWD between", value1, value2, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDsConnPswdNotBetween(String value1, String value2) {
            addCriterion("DS_CONN_PSWD not between", value1, value2, "dsConnPswd");
            return (Criteria) this;
        }

        public Criteria andDbTpIsNull() {
            addCriterion("DB_TP is null");
            return (Criteria) this;
        }

        public Criteria andDbTpIsNotNull() {
            addCriterion("DB_TP is not null");
            return (Criteria) this;
        }

        public Criteria andDbTpEqualTo(String value) {
            addCriterion("DB_TP =", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpNotEqualTo(String value) {
            addCriterion("DB_TP <>", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpGreaterThan(String value) {
            addCriterion("DB_TP >", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpGreaterThanOrEqualTo(String value) {
            addCriterion("DB_TP >=", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpLessThan(String value) {
            addCriterion("DB_TP <", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpLessThanOrEqualTo(String value) {
            addCriterion("DB_TP <=", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpLike(String value) {
            addCriterion("DB_TP like", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpNotLike(String value) {
            addCriterion("DB_TP not like", value, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpIn(List<String> values) {
            addCriterion("DB_TP in", values, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpNotIn(List<String> values) {
            addCriterion("DB_TP not in", values, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpBetween(String value1, String value2) {
            addCriterion("DB_TP between", value1, value2, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbTpNotBetween(String value1, String value2) {
            addCriterion("DB_TP not between", value1, value2, "dbTp");
            return (Criteria) this;
        }

        public Criteria andDbNmIsNull() {
            addCriterion("DB_NM is null");
            return (Criteria) this;
        }

        public Criteria andDbNmIsNotNull() {
            addCriterion("DB_NM is not null");
            return (Criteria) this;
        }

        public Criteria andDbNmEqualTo(String value) {
            addCriterion("DB_NM =", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmNotEqualTo(String value) {
            addCriterion("DB_NM <>", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmGreaterThan(String value) {
            addCriterion("DB_NM >", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmGreaterThanOrEqualTo(String value) {
            addCriterion("DB_NM >=", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmLessThan(String value) {
            addCriterion("DB_NM <", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmLessThanOrEqualTo(String value) {
            addCriterion("DB_NM <=", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmLike(String value) {
            addCriterion("DB_NM like", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmNotLike(String value) {
            addCriterion("DB_NM not like", value, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmIn(List<String> values) {
            addCriterion("DB_NM in", values, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmNotIn(List<String> values) {
            addCriterion("DB_NM not in", values, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmBetween(String value1, String value2) {
            addCriterion("DB_NM between", value1, value2, "dbNm");
            return (Criteria) this;
        }

        public Criteria andDbNmNotBetween(String value1, String value2) {
            addCriterion("DB_NM not between", value1, value2, "dbNm");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNull() {
            addCriterion("REG_DT is null");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNotNull() {
            addCriterion("REG_DT is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtEqualTo(Date value) {
            addCriterion("REG_DT =", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotEqualTo(Date value) {
            addCriterion("REG_DT <>", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThan(Date value) {
            addCriterion("REG_DT >", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DT >=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThan(Date value) {
            addCriterion("REG_DT <", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThanOrEqualTo(Date value) {
            addCriterion("REG_DT <=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtIn(List<Date> values) {
            addCriterion("REG_DT in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotIn(List<Date> values) {
            addCriterion("REG_DT not in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtBetween(Date value1, Date value2) {
            addCriterion("REG_DT between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotBetween(Date value1, Date value2) {
            addCriterion("REG_DT not between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andModDtIsNull() {
            addCriterion("MOD_DT is null");
            return (Criteria) this;
        }

        public Criteria andModDtIsNotNull() {
            addCriterion("MOD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andModDtEqualTo(Date value) {
            addCriterion("MOD_DT =", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotEqualTo(Date value) {
            addCriterion("MOD_DT <>", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThan(Date value) {
            addCriterion("MOD_DT >", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DT >=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThan(Date value) {
            addCriterion("MOD_DT <", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DT <=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtIn(List<Date> values) {
            addCriterion("MOD_DT in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotIn(List<Date> values) {
            addCriterion("MOD_DT not in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtBetween(Date value1, Date value2) {
            addCriterion("MOD_DT between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DT not between", value1, value2, "modDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 09 16:00:16 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}