package com.nomad.data.agent.domain.dao.common;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AIP_DOCKER_IMAGE
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 22 17:39:33 KST 2020
 */
public class AipDockerImage extends AipDockerImageKey {
    /**
     */
    private String imgTp;

    /**
     */
    private String imgNm;

    /**
     */
    private String imgDesc;

    /**
     */
    private String dckrImgTag;

    /**
     */
    private String dckrImgNm;

    /**
     */
    private String regId;

    /**
     */
    private String delFl;

    /**
     */
    private Date regDt;

    /**
     */
    private Date modDt;

    /**
     */
    private String advOpt;

    /**
     */
    private String procTp;

    /**
     */
    private BigDecimal imgPort;

    /**
     */
    public String getImgTp() {
        return imgTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.IMG_TP
     *
     * @param imgTp the value for AIP_DOCKER_IMAGE.IMG_TP
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setImgTp(String imgTp) {
        this.imgTp = imgTp == null ? null : imgTp.trim();
    }

    /**
     */
    public String getImgNm() {
        return imgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.IMG_NM
     *
     * @param imgNm the value for AIP_DOCKER_IMAGE.IMG_NM
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setImgNm(String imgNm) {
        this.imgNm = imgNm == null ? null : imgNm.trim();
    }

    /**
     */
    public String getImgDesc() {
        return imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.IMG_DESC
     *
     * @param imgDesc the value for AIP_DOCKER_IMAGE.IMG_DESC
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc == null ? null : imgDesc.trim();
    }

    /**
     */
    public String getDckrImgTag() {
        return dckrImgTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.DCKR_IMG_TAG
     *
     * @param dckrImgTag the value for AIP_DOCKER_IMAGE.DCKR_IMG_TAG
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setDckrImgTag(String dckrImgTag) {
        this.dckrImgTag = dckrImgTag == null ? null : dckrImgTag.trim();
    }

    /**
     */
    public String getDckrImgNm() {
        return dckrImgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.DCKR_IMG_NM
     *
     * @param dckrImgNm the value for AIP_DOCKER_IMAGE.DCKR_IMG_NM
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setDckrImgNm(String dckrImgNm) {
        this.dckrImgNm = dckrImgNm == null ? null : dckrImgNm.trim();
    }

    /**
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.REG_ID
     *
     * @param regId the value for AIP_DOCKER_IMAGE.REG_ID
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     */
    public String getDelFl() {
        return delFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.DEL_FL
     *
     * @param delFl the value for AIP_DOCKER_IMAGE.DEL_FL
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setDelFl(String delFl) {
        this.delFl = delFl == null ? null : delFl.trim();
    }

    /**
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.REG_DT
     *
     * @param regDt the value for AIP_DOCKER_IMAGE.REG_DT
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.MOD_DT
     *
     * @param modDt the value for AIP_DOCKER_IMAGE.MOD_DT
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }

    /**
     */
    public String getAdvOpt() {
        return advOpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.ADV_OPT
     *
     * @param advOpt the value for AIP_DOCKER_IMAGE.ADV_OPT
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setAdvOpt(String advOpt) {
        this.advOpt = advOpt == null ? null : advOpt.trim();
    }

    /**
     */
    public String getProcTp() {
        return procTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.PROC_TP
     *
     * @param procTp the value for AIP_DOCKER_IMAGE.PROC_TP
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setProcTp(String procTp) {
        this.procTp = procTp == null ? null : procTp.trim();
    }

    /**
     */
    public BigDecimal getImgPort() {
        return imgPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_DOCKER_IMAGE.IMG_PORT
     *
     * @param imgPort the value for AIP_DOCKER_IMAGE.IMG_PORT
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    public void setImgPort(BigDecimal imgPort) {
        this.imgPort = imgPort;
    }
}