package com.nomad.data.agent.domain.dao.common;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table aip_data_set_file_map
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 29 17:19:36 KST 2020
 */
public class AipDataSetFileMapKey {
    /**
     *   데이터셋파일맵아이디
     */
    private String dataFileMapId;

    /**
     *   데이터셋파일맵아이디
     */
    public String getDataFileMapId() {
        return dataFileMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.DATA_FILE_MAP_ID
     *
     * @param dataFileMapId the value for aip_data_set_file_map.DATA_FILE_MAP_ID
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setDataFileMapId(String dataFileMapId) {
        this.dataFileMapId = dataFileMapId == null ? null : dataFileMapId.trim();
    }
}