package com.nomad.data.agent.domain.dao.common;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AipDataSetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public AipDataSetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDataIdIsNull() {
            addCriterion("DATA_ID is null");
            return (Criteria) this;
        }

        public Criteria andDataIdIsNotNull() {
            addCriterion("DATA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDataIdEqualTo(String value) {
            addCriterion("DATA_ID =", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotEqualTo(String value) {
            addCriterion("DATA_ID <>", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdGreaterThan(String value) {
            addCriterion("DATA_ID >", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_ID >=", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdLessThan(String value) {
            addCriterion("DATA_ID <", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdLessThanOrEqualTo(String value) {
            addCriterion("DATA_ID <=", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdLike(String value) {
            addCriterion("DATA_ID like", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotLike(String value) {
            addCriterion("DATA_ID not like", value, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdIn(List<String> values) {
            addCriterion("DATA_ID in", values, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotIn(List<String> values) {
            addCriterion("DATA_ID not in", values, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdBetween(String value1, String value2) {
            addCriterion("DATA_ID between", value1, value2, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataIdNotBetween(String value1, String value2) {
            addCriterion("DATA_ID not between", value1, value2, "dataId");
            return (Criteria) this;
        }

        public Criteria andDataNmIsNull() {
            addCriterion("DATA_NM is null");
            return (Criteria) this;
        }

        public Criteria andDataNmIsNotNull() {
            addCriterion("DATA_NM is not null");
            return (Criteria) this;
        }

        public Criteria andDataNmEqualTo(String value) {
            addCriterion("DATA_NM =", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotEqualTo(String value) {
            addCriterion("DATA_NM <>", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmGreaterThan(String value) {
            addCriterion("DATA_NM >", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_NM >=", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmLessThan(String value) {
            addCriterion("DATA_NM <", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmLessThanOrEqualTo(String value) {
            addCriterion("DATA_NM <=", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmLike(String value) {
            addCriterion("DATA_NM like", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotLike(String value) {
            addCriterion("DATA_NM not like", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmIn(List<String> values) {
            addCriterion("DATA_NM in", values, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotIn(List<String> values) {
            addCriterion("DATA_NM not in", values, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmBetween(String value1, String value2) {
            addCriterion("DATA_NM between", value1, value2, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotBetween(String value1, String value2) {
            addCriterion("DATA_NM not between", value1, value2, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataDescIsNull() {
            addCriterion("DATA_DESC is null");
            return (Criteria) this;
        }

        public Criteria andDataDescIsNotNull() {
            addCriterion("DATA_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andDataDescEqualTo(String value) {
            addCriterion("DATA_DESC =", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescNotEqualTo(String value) {
            addCriterion("DATA_DESC <>", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescGreaterThan(String value) {
            addCriterion("DATA_DESC >", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_DESC >=", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescLessThan(String value) {
            addCriterion("DATA_DESC <", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescLessThanOrEqualTo(String value) {
            addCriterion("DATA_DESC <=", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescLike(String value) {
            addCriterion("DATA_DESC like", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescNotLike(String value) {
            addCriterion("DATA_DESC not like", value, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescIn(List<String> values) {
            addCriterion("DATA_DESC in", values, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescNotIn(List<String> values) {
            addCriterion("DATA_DESC not in", values, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescBetween(String value1, String value2) {
            addCriterion("DATA_DESC between", value1, value2, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataDescNotBetween(String value1, String value2) {
            addCriterion("DATA_DESC not between", value1, value2, "dataDesc");
            return (Criteria) this;
        }

        public Criteria andDataTpIsNull() {
            addCriterion("DATA_TP is null");
            return (Criteria) this;
        }

        public Criteria andDataTpIsNotNull() {
            addCriterion("DATA_TP is not null");
            return (Criteria) this;
        }

        public Criteria andDataTpEqualTo(String value) {
            addCriterion("DATA_TP =", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpNotEqualTo(String value) {
            addCriterion("DATA_TP <>", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpGreaterThan(String value) {
            addCriterion("DATA_TP >", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_TP >=", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpLessThan(String value) {
            addCriterion("DATA_TP <", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpLessThanOrEqualTo(String value) {
            addCriterion("DATA_TP <=", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpLike(String value) {
            addCriterion("DATA_TP like", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpNotLike(String value) {
            addCriterion("DATA_TP not like", value, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpIn(List<String> values) {
            addCriterion("DATA_TP in", values, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpNotIn(List<String> values) {
            addCriterion("DATA_TP not in", values, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpBetween(String value1, String value2) {
            addCriterion("DATA_TP between", value1, value2, "dataTp");
            return (Criteria) this;
        }

        public Criteria andDataTpNotBetween(String value1, String value2) {
            addCriterion("DATA_TP not between", value1, value2, "dataTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpIsNull() {
            addCriterion("QUERY_DB_TP is null");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpIsNotNull() {
            addCriterion("QUERY_DB_TP is not null");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpEqualTo(String value) {
            addCriterion("QUERY_DB_TP =", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpNotEqualTo(String value) {
            addCriterion("QUERY_DB_TP <>", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpGreaterThan(String value) {
            addCriterion("QUERY_DB_TP >", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_DB_TP >=", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpLessThan(String value) {
            addCriterion("QUERY_DB_TP <", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpLessThanOrEqualTo(String value) {
            addCriterion("QUERY_DB_TP <=", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpLike(String value) {
            addCriterion("QUERY_DB_TP like", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpNotLike(String value) {
            addCriterion("QUERY_DB_TP not like", value, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpIn(List<String> values) {
            addCriterion("QUERY_DB_TP in", values, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpNotIn(List<String> values) {
            addCriterion("QUERY_DB_TP not in", values, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpBetween(String value1, String value2) {
            addCriterion("QUERY_DB_TP between", value1, value2, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryDbTpNotBetween(String value1, String value2) {
            addCriterion("QUERY_DB_TP not between", value1, value2, "queryDbTp");
            return (Criteria) this;
        }

        public Criteria andQueryStrIsNull() {
            addCriterion("QUERY_STR is null");
            return (Criteria) this;
        }

        public Criteria andQueryStrIsNotNull() {
            addCriterion("QUERY_STR is not null");
            return (Criteria) this;
        }

        public Criteria andQueryStrEqualTo(String value) {
            addCriterion("QUERY_STR =", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrNotEqualTo(String value) {
            addCriterion("QUERY_STR <>", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrGreaterThan(String value) {
            addCriterion("QUERY_STR >", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_STR >=", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrLessThan(String value) {
            addCriterion("QUERY_STR <", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrLessThanOrEqualTo(String value) {
            addCriterion("QUERY_STR <=", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrLike(String value) {
            addCriterion("QUERY_STR like", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrNotLike(String value) {
            addCriterion("QUERY_STR not like", value, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrIn(List<String> values) {
            addCriterion("QUERY_STR in", values, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrNotIn(List<String> values) {
            addCriterion("QUERY_STR not in", values, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrBetween(String value1, String value2) {
            addCriterion("QUERY_STR between", value1, value2, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStrNotBetween(String value1, String value2) {
            addCriterion("QUERY_STR not between", value1, value2, "queryStr");
            return (Criteria) this;
        }

        public Criteria andQueryStsIsNull() {
            addCriterion("QUERY_STS is null");
            return (Criteria) this;
        }

        public Criteria andQueryStsIsNotNull() {
            addCriterion("QUERY_STS is not null");
            return (Criteria) this;
        }

        public Criteria andQueryStsEqualTo(String value) {
            addCriterion("QUERY_STS =", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsNotEqualTo(String value) {
            addCriterion("QUERY_STS <>", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsGreaterThan(String value) {
            addCriterion("QUERY_STS >", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_STS >=", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsLessThan(String value) {
            addCriterion("QUERY_STS <", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsLessThanOrEqualTo(String value) {
            addCriterion("QUERY_STS <=", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsLike(String value) {
            addCriterion("QUERY_STS like", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsNotLike(String value) {
            addCriterion("QUERY_STS not like", value, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsIn(List<String> values) {
            addCriterion("QUERY_STS in", values, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsNotIn(List<String> values) {
            addCriterion("QUERY_STS not in", values, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsBetween(String value1, String value2) {
            addCriterion("QUERY_STS between", value1, value2, "querySts");
            return (Criteria) this;
        }

        public Criteria andQueryStsNotBetween(String value1, String value2) {
            addCriterion("QUERY_STS not between", value1, value2, "querySts");
            return (Criteria) this;
        }

        public Criteria andFileNmIsNull() {
            addCriterion("FILE_NM is null");
            return (Criteria) this;
        }

        public Criteria andFileNmIsNotNull() {
            addCriterion("FILE_NM is not null");
            return (Criteria) this;
        }

        public Criteria andFileNmEqualTo(String value) {
            addCriterion("FILE_NM =", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotEqualTo(String value) {
            addCriterion("FILE_NM <>", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmGreaterThan(String value) {
            addCriterion("FILE_NM >", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_NM >=", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmLessThan(String value) {
            addCriterion("FILE_NM <", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmLessThanOrEqualTo(String value) {
            addCriterion("FILE_NM <=", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmLike(String value) {
            addCriterion("FILE_NM like", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotLike(String value) {
            addCriterion("FILE_NM not like", value, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmIn(List<String> values) {
            addCriterion("FILE_NM in", values, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotIn(List<String> values) {
            addCriterion("FILE_NM not in", values, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmBetween(String value1, String value2) {
            addCriterion("FILE_NM between", value1, value2, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFileNmNotBetween(String value1, String value2) {
            addCriterion("FILE_NM not between", value1, value2, "fileNm");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("FILE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("FILE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("FILE_PATH =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("FILE_PATH <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("FILE_PATH >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_PATH >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("FILE_PATH <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("FILE_PATH <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("FILE_PATH like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("FILE_PATH not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("FILE_PATH in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("FILE_PATH not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("FILE_PATH between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("FILE_PATH not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFileSzIsNull() {
            addCriterion("FILE_SZ is null");
            return (Criteria) this;
        }

        public Criteria andFileSzIsNotNull() {
            addCriterion("FILE_SZ is not null");
            return (Criteria) this;
        }

        public Criteria andFileSzEqualTo(Long value) {
            addCriterion("FILE_SZ =", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzNotEqualTo(Long value) {
            addCriterion("FILE_SZ <>", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzGreaterThan(Long value) {
            addCriterion("FILE_SZ >", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzGreaterThanOrEqualTo(Long value) {
            addCriterion("FILE_SZ >=", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzLessThan(Long value) {
            addCriterion("FILE_SZ <", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzLessThanOrEqualTo(Long value) {
            addCriterion("FILE_SZ <=", value, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzIn(List<Long> values) {
            addCriterion("FILE_SZ in", values, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzNotIn(List<Long> values) {
            addCriterion("FILE_SZ not in", values, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzBetween(Long value1, Long value2) {
            addCriterion("FILE_SZ between", value1, value2, "fileSz");
            return (Criteria) this;
        }

        public Criteria andFileSzNotBetween(Long value1, Long value2) {
            addCriterion("FILE_SZ not between", value1, value2, "fileSz");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("OWNER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("OWNER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(String value) {
            addCriterion("OWNER_ID =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(String value) {
            addCriterion("OWNER_ID <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(String value) {
            addCriterion("OWNER_ID >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER_ID >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(String value) {
            addCriterion("OWNER_ID <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("OWNER_ID <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLike(String value) {
            addCriterion("OWNER_ID like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotLike(String value) {
            addCriterion("OWNER_ID not like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<String> values) {
            addCriterion("OWNER_ID in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<String> values) {
            addCriterion("OWNER_ID not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(String value1, String value2) {
            addCriterion("OWNER_ID between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(String value1, String value2) {
            addCriterion("OWNER_ID not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNull() {
            addCriterion("REG_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNotNull() {
            addCriterion("REG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegIdEqualTo(String value) {
            addCriterion("REG_ID =", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotEqualTo(String value) {
            addCriterion("REG_ID <>", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThan(String value) {
            addCriterion("REG_ID >", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThanOrEqualTo(String value) {
            addCriterion("REG_ID >=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThan(String value) {
            addCriterion("REG_ID <", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThanOrEqualTo(String value) {
            addCriterion("REG_ID <=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLike(String value) {
            addCriterion("REG_ID like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotLike(String value) {
            addCriterion("REG_ID not like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdIn(List<String> values) {
            addCriterion("REG_ID in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotIn(List<String> values) {
            addCriterion("REG_ID not in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdBetween(String value1, String value2) {
            addCriterion("REG_ID between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotBetween(String value1, String value2) {
            addCriterion("REG_ID not between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andAccAuthIsNull() {
            addCriterion("ACC_AUTH is null");
            return (Criteria) this;
        }

        public Criteria andAccAuthIsNotNull() {
            addCriterion("ACC_AUTH is not null");
            return (Criteria) this;
        }

        public Criteria andAccAuthEqualTo(Integer value) {
            addCriterion("ACC_AUTH =", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthNotEqualTo(Integer value) {
            addCriterion("ACC_AUTH <>", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthGreaterThan(Integer value) {
            addCriterion("ACC_AUTH >", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACC_AUTH >=", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthLessThan(Integer value) {
            addCriterion("ACC_AUTH <", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthLessThanOrEqualTo(Integer value) {
            addCriterion("ACC_AUTH <=", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthIn(List<Integer> values) {
            addCriterion("ACC_AUTH in", values, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthNotIn(List<Integer> values) {
            addCriterion("ACC_AUTH not in", values, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthBetween(Integer value1, Integer value2) {
            addCriterion("ACC_AUTH between", value1, value2, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthNotBetween(Integer value1, Integer value2) {
            addCriterion("ACC_AUTH not between", value1, value2, "accAuth");
            return (Criteria) this;
        }

        public Criteria andExptStDtIsNull() {
            addCriterion("EXPT_ST_DT is null");
            return (Criteria) this;
        }

        public Criteria andExptStDtIsNotNull() {
            addCriterion("EXPT_ST_DT is not null");
            return (Criteria) this;
        }

        public Criteria andExptStDtEqualTo(String value) {
            addCriterion("EXPT_ST_DT =", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotEqualTo(String value) {
            addCriterion("EXPT_ST_DT <>", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtGreaterThan(String value) {
            addCriterion("EXPT_ST_DT >", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtGreaterThanOrEqualTo(String value) {
            addCriterion("EXPT_ST_DT >=", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtLessThan(String value) {
            addCriterion("EXPT_ST_DT <", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtLessThanOrEqualTo(String value) {
            addCriterion("EXPT_ST_DT <=", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtLike(String value) {
            addCriterion("EXPT_ST_DT like", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotLike(String value) {
            addCriterion("EXPT_ST_DT not like", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtIn(List<String> values) {
            addCriterion("EXPT_ST_DT in", values, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotIn(List<String> values) {
            addCriterion("EXPT_ST_DT not in", values, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtBetween(String value1, String value2) {
            addCriterion("EXPT_ST_DT between", value1, value2, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotBetween(String value1, String value2) {
            addCriterion("EXPT_ST_DT not between", value1, value2, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtIsNull() {
            addCriterion("EXPT_ED_DT is null");
            return (Criteria) this;
        }

        public Criteria andExptEdDtIsNotNull() {
            addCriterion("EXPT_ED_DT is not null");
            return (Criteria) this;
        }

        public Criteria andExptEdDtEqualTo(String value) {
            addCriterion("EXPT_ED_DT =", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotEqualTo(String value) {
            addCriterion("EXPT_ED_DT <>", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtGreaterThan(String value) {
            addCriterion("EXPT_ED_DT >", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtGreaterThanOrEqualTo(String value) {
            addCriterion("EXPT_ED_DT >=", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtLessThan(String value) {
            addCriterion("EXPT_ED_DT <", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtLessThanOrEqualTo(String value) {
            addCriterion("EXPT_ED_DT <=", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtLike(String value) {
            addCriterion("EXPT_ED_DT like", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotLike(String value) {
            addCriterion("EXPT_ED_DT not like", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtIn(List<String> values) {
            addCriterion("EXPT_ED_DT in", values, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotIn(List<String> values) {
            addCriterion("EXPT_ED_DT not in", values, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtBetween(String value1, String value2) {
            addCriterion("EXPT_ED_DT between", value1, value2, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotBetween(String value1, String value2) {
            addCriterion("EXPT_ED_DT not between", value1, value2, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andPubFlIsNull() {
            addCriterion("PUB_FL is null");
            return (Criteria) this;
        }

        public Criteria andPubFlIsNotNull() {
            addCriterion("PUB_FL is not null");
            return (Criteria) this;
        }

        public Criteria andPubFlEqualTo(String value) {
            addCriterion("PUB_FL =", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlNotEqualTo(String value) {
            addCriterion("PUB_FL <>", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlGreaterThan(String value) {
            addCriterion("PUB_FL >", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlGreaterThanOrEqualTo(String value) {
            addCriterion("PUB_FL >=", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlLessThan(String value) {
            addCriterion("PUB_FL <", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlLessThanOrEqualTo(String value) {
            addCriterion("PUB_FL <=", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlLike(String value) {
            addCriterion("PUB_FL like", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlNotLike(String value) {
            addCriterion("PUB_FL not like", value, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlIn(List<String> values) {
            addCriterion("PUB_FL in", values, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlNotIn(List<String> values) {
            addCriterion("PUB_FL not in", values, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlBetween(String value1, String value2) {
            addCriterion("PUB_FL between", value1, value2, "pubFl");
            return (Criteria) this;
        }

        public Criteria andPubFlNotBetween(String value1, String value2) {
            addCriterion("PUB_FL not between", value1, value2, "pubFl");
            return (Criteria) this;
        }

        public Criteria andDelFlIsNull() {
            addCriterion("DEL_FL is null");
            return (Criteria) this;
        }

        public Criteria andDelFlIsNotNull() {
            addCriterion("DEL_FL is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlEqualTo(String value) {
            addCriterion("DEL_FL =", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotEqualTo(String value) {
            addCriterion("DEL_FL <>", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlGreaterThan(String value) {
            addCriterion("DEL_FL >", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_FL >=", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLessThan(String value) {
            addCriterion("DEL_FL <", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLessThanOrEqualTo(String value) {
            addCriterion("DEL_FL <=", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLike(String value) {
            addCriterion("DEL_FL like", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotLike(String value) {
            addCriterion("DEL_FL not like", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlIn(List<String> values) {
            addCriterion("DEL_FL in", values, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotIn(List<String> values) {
            addCriterion("DEL_FL not in", values, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlBetween(String value1, String value2) {
            addCriterion("DEL_FL between", value1, value2, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotBetween(String value1, String value2) {
            addCriterion("DEL_FL not between", value1, value2, "delFl");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNull() {
            addCriterion("REG_DT is null");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNotNull() {
            addCriterion("REG_DT is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtEqualTo(Date value) {
            addCriterion("REG_DT =", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotEqualTo(Date value) {
            addCriterion("REG_DT <>", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThan(Date value) {
            addCriterion("REG_DT >", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DT >=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThan(Date value) {
            addCriterion("REG_DT <", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThanOrEqualTo(Date value) {
            addCriterion("REG_DT <=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtIn(List<Date> values) {
            addCriterion("REG_DT in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotIn(List<Date> values) {
            addCriterion("REG_DT not in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtBetween(Date value1, Date value2) {
            addCriterion("REG_DT between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotBetween(Date value1, Date value2) {
            addCriterion("REG_DT not between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andModDtIsNull() {
            addCriterion("MOD_DT is null");
            return (Criteria) this;
        }

        public Criteria andModDtIsNotNull() {
            addCriterion("MOD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andModDtEqualTo(Date value) {
            addCriterion("MOD_DT =", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotEqualTo(Date value) {
            addCriterion("MOD_DT <>", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThan(Date value) {
            addCriterion("MOD_DT >", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DT >=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThan(Date value) {
            addCriterion("MOD_DT <", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DT <=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtIn(List<Date> values) {
            addCriterion("MOD_DT in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotIn(List<Date> values) {
            addCriterion("MOD_DT not in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtBetween(Date value1, Date value2) {
            addCriterion("MOD_DT between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DT not between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andDsIdIsNull() {
            addCriterion("ds_id is null");
            return (Criteria) this;
        }

        public Criteria andDsIdIsNotNull() {
            addCriterion("ds_id is not null");
            return (Criteria) this;
        }

        public Criteria andDsIdEqualTo(String value) {
            addCriterion("ds_id =", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotEqualTo(String value) {
            addCriterion("ds_id <>", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdGreaterThan(String value) {
            addCriterion("ds_id >", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdGreaterThanOrEqualTo(String value) {
            addCriterion("ds_id >=", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLessThan(String value) {
            addCriterion("ds_id <", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLessThanOrEqualTo(String value) {
            addCriterion("ds_id <=", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdLike(String value) {
            addCriterion("ds_id like", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotLike(String value) {
            addCriterion("ds_id not like", value, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdIn(List<String> values) {
            addCriterion("ds_id in", values, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotIn(List<String> values) {
            addCriterion("ds_id not in", values, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdBetween(String value1, String value2) {
            addCriterion("ds_id between", value1, value2, "dsId");
            return (Criteria) this;
        }

        public Criteria andDsIdNotBetween(String value1, String value2) {
            addCriterion("ds_id not between", value1, value2, "dsId");
            return (Criteria) this;
        }

        public Criteria andDataCntIsNull() {
            addCriterion("data_cnt is null");
            return (Criteria) this;
        }

        public Criteria andDataCntIsNotNull() {
            addCriterion("data_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andDataCntEqualTo(Integer value) {
            addCriterion("data_cnt =", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntNotEqualTo(Integer value) {
            addCriterion("data_cnt <>", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntGreaterThan(Integer value) {
            addCriterion("data_cnt >", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("data_cnt >=", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntLessThan(Integer value) {
            addCriterion("data_cnt <", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntLessThanOrEqualTo(Integer value) {
            addCriterion("data_cnt <=", value, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntIn(List<Integer> values) {
            addCriterion("data_cnt in", values, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntNotIn(List<Integer> values) {
            addCriterion("data_cnt not in", values, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntBetween(Integer value1, Integer value2) {
            addCriterion("data_cnt between", value1, value2, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andDataCntNotBetween(Integer value1, Integer value2) {
            addCriterion("data_cnt not between", value1, value2, "dataCnt");
            return (Criteria) this;
        }

        public Criteria andScheduleFlIsNull() {
            addCriterion("SCHEDULE_FL is null");
            return (Criteria) this;
        }

        public Criteria andScheduleFlIsNotNull() {
            addCriterion("SCHEDULE_FL is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleFlEqualTo(String value) {
            addCriterion("SCHEDULE_FL =", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlNotEqualTo(String value) {
            addCriterion("SCHEDULE_FL <>", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlGreaterThan(String value) {
            addCriterion("SCHEDULE_FL >", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_FL >=", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlLessThan(String value) {
            addCriterion("SCHEDULE_FL <", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_FL <=", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlLike(String value) {
            addCriterion("SCHEDULE_FL like", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlNotLike(String value) {
            addCriterion("SCHEDULE_FL not like", value, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlIn(List<String> values) {
            addCriterion("SCHEDULE_FL in", values, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlNotIn(List<String> values) {
            addCriterion("SCHEDULE_FL not in", values, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlBetween(String value1, String value2) {
            addCriterion("SCHEDULE_FL between", value1, value2, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleFlNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_FL not between", value1, value2, "scheduleFl");
            return (Criteria) this;
        }

        public Criteria andScheduleTpIsNull() {
            addCriterion("SCHEDULE_TP is null");
            return (Criteria) this;
        }

        public Criteria andScheduleTpIsNotNull() {
            addCriterion("SCHEDULE_TP is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleTpEqualTo(String value) {
            addCriterion("SCHEDULE_TP =", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpNotEqualTo(String value) {
            addCriterion("SCHEDULE_TP <>", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpGreaterThan(String value) {
            addCriterion("SCHEDULE_TP >", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_TP >=", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpLessThan(String value) {
            addCriterion("SCHEDULE_TP <", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_TP <=", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpLike(String value) {
            addCriterion("SCHEDULE_TP like", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpNotLike(String value) {
            addCriterion("SCHEDULE_TP not like", value, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpIn(List<String> values) {
            addCriterion("SCHEDULE_TP in", values, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpNotIn(List<String> values) {
            addCriterion("SCHEDULE_TP not in", values, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpBetween(String value1, String value2) {
            addCriterion("SCHEDULE_TP between", value1, value2, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleTpNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_TP not between", value1, value2, "scheduleTp");
            return (Criteria) this;
        }

        public Criteria andScheduleHourIsNull() {
            addCriterion("SCHEDULE_HOUR is null");
            return (Criteria) this;
        }

        public Criteria andScheduleHourIsNotNull() {
            addCriterion("SCHEDULE_HOUR is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleHourEqualTo(String value) {
            addCriterion("SCHEDULE_HOUR =", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourNotEqualTo(String value) {
            addCriterion("SCHEDULE_HOUR <>", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourGreaterThan(String value) {
            addCriterion("SCHEDULE_HOUR >", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_HOUR >=", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourLessThan(String value) {
            addCriterion("SCHEDULE_HOUR <", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_HOUR <=", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourLike(String value) {
            addCriterion("SCHEDULE_HOUR like", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourNotLike(String value) {
            addCriterion("SCHEDULE_HOUR not like", value, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourIn(List<String> values) {
            addCriterion("SCHEDULE_HOUR in", values, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourNotIn(List<String> values) {
            addCriterion("SCHEDULE_HOUR not in", values, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourBetween(String value1, String value2) {
            addCriterion("SCHEDULE_HOUR between", value1, value2, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleHourNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_HOUR not between", value1, value2, "scheduleHour");
            return (Criteria) this;
        }

        public Criteria andScheduleMinIsNull() {
            addCriterion("SCHEDULE_MIN is null");
            return (Criteria) this;
        }

        public Criteria andScheduleMinIsNotNull() {
            addCriterion("SCHEDULE_MIN is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleMinEqualTo(String value) {
            addCriterion("SCHEDULE_MIN =", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinNotEqualTo(String value) {
            addCriterion("SCHEDULE_MIN <>", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinGreaterThan(String value) {
            addCriterion("SCHEDULE_MIN >", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_MIN >=", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinLessThan(String value) {
            addCriterion("SCHEDULE_MIN <", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_MIN <=", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinLike(String value) {
            addCriterion("SCHEDULE_MIN like", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinNotLike(String value) {
            addCriterion("SCHEDULE_MIN not like", value, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinIn(List<String> values) {
            addCriterion("SCHEDULE_MIN in", values, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinNotIn(List<String> values) {
            addCriterion("SCHEDULE_MIN not in", values, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinBetween(String value1, String value2) {
            addCriterion("SCHEDULE_MIN between", value1, value2, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleMinNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_MIN not between", value1, value2, "scheduleMin");
            return (Criteria) this;
        }

        public Criteria andScheduleDayIsNull() {
            addCriterion("SCHEDULE_DAY is null");
            return (Criteria) this;
        }

        public Criteria andScheduleDayIsNotNull() {
            addCriterion("SCHEDULE_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleDayEqualTo(String value) {
            addCriterion("SCHEDULE_DAY =", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayNotEqualTo(String value) {
            addCriterion("SCHEDULE_DAY <>", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayGreaterThan(String value) {
            addCriterion("SCHEDULE_DAY >", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_DAY >=", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayLessThan(String value) {
            addCriterion("SCHEDULE_DAY <", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_DAY <=", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayLike(String value) {
            addCriterion("SCHEDULE_DAY like", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayNotLike(String value) {
            addCriterion("SCHEDULE_DAY not like", value, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayIn(List<String> values) {
            addCriterion("SCHEDULE_DAY in", values, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayNotIn(List<String> values) {
            addCriterion("SCHEDULE_DAY not in", values, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayBetween(String value1, String value2) {
            addCriterion("SCHEDULE_DAY between", value1, value2, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_DAY not between", value1, value2, "scheduleDay");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekIsNull() {
            addCriterion("SCHEDULE_DAY_OF_WEEK is null");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekIsNotNull() {
            addCriterion("SCHEDULE_DAY_OF_WEEK is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekEqualTo(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK =", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekNotEqualTo(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK <>", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekGreaterThan(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK >", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK >=", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekLessThan(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK <", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK <=", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekLike(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK like", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekNotLike(String value) {
            addCriterion("SCHEDULE_DAY_OF_WEEK not like", value, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekIn(List<String> values) {
            addCriterion("SCHEDULE_DAY_OF_WEEK in", values, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekNotIn(List<String> values) {
            addCriterion("SCHEDULE_DAY_OF_WEEK not in", values, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekBetween(String value1, String value2) {
            addCriterion("SCHEDULE_DAY_OF_WEEK between", value1, value2, "scheduleDayOfWeek");
            return (Criteria) this;
        }

        public Criteria andScheduleDayOfWeekNotBetween(String value1, String value2) {
            addCriterion("SCHEDULE_DAY_OF_WEEK not between", value1, value2, "scheduleDayOfWeek");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aip_data_set
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 29 17:19:36 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aip_data_set
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}