package com.nomad.data.agent.domain.dao.common;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table aip_data_set_file_map
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 29 17:19:36 KST 2020
 */
public class AipDataSetFileMap extends AipDataSetFileMapKey {
    /**
     *   데이터셋아이디
     */
    private String dataId;

    /**
     *   파일이름
     */
    private String fileNm;

    /**
     *   파일경로
     */
    private String filePath;

    /**
     *   파일크기
     */
    private Long fileSz;

    /**
     *   데이터 건수
     */
    private Long dataCnt;

    /**
     *   등록일
     */
    private Date regDt;

    /**
     *   수정일
     */
    private Date modDt;

    /**
     *   데이터셋아이디
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.DATA_ID
     *
     * @param dataId the value for aip_data_set_file_map.DATA_ID
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     *   파일이름
     */
    public String getFileNm() {
        return fileNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.FILE_NM
     *
     * @param fileNm the value for aip_data_set_file_map.FILE_NM
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setFileNm(String fileNm) {
        this.fileNm = fileNm == null ? null : fileNm.trim();
    }

    /**
     *   파일경로
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.FILE_PATH
     *
     * @param filePath the value for aip_data_set_file_map.FILE_PATH
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     *   파일크기
     */
    public Long getFileSz() {
        return fileSz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.FILE_SZ
     *
     * @param fileSz the value for aip_data_set_file_map.FILE_SZ
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setFileSz(Long fileSz) {
        this.fileSz = fileSz;
    }

    /**
     *   데이터 건수
     */
    public Long getDataCnt() {
        return dataCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.DATA_CNT
     *
     * @param dataCnt the value for aip_data_set_file_map.DATA_CNT
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setDataCnt(Long dataCnt) {
        this.dataCnt = dataCnt;
    }

    /**
     *   등록일
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.REG_DT
     *
     * @param regDt the value for aip_data_set_file_map.REG_DT
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     *   수정일
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aip_data_set_file_map.MOD_DT
     *
     * @param modDt the value for aip_data_set_file_map.MOD_DT
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }
}