package com.nomad.data.agent.domain.dao.common;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AIP_LOGS
 *
 * @mbg.generated do_not_delete_during_merge Thu Apr 09 11:36:59 KST 2020
 */
public class AipLogsKey {
    /**
     */
    private String logId;

    /**
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_LOGS.LOG_ID
     *
     * @param logId the value for AIP_LOGS.LOG_ID
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }
}