package com.nomad.data.agent.domain.dao.common;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AIP_LOGS
 *
 * @mbg.generated do_not_delete_during_merge Thu Apr 09 11:36:59 KST 2020
 */
public class AipLogs extends AipLogsKey {
    /**
     */
    private String logTp;

    /**
     */
    private String logStr;

    /**
     */
    private String userId;

    /**
     */
    private String logDetail;

    /**
     */
    private Date regDt;

    /**
     */
    private Date modDt;

    /**
     */
    public String getLogTp() {
        return logTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_LOGS.LOG_TP
     *
     * @param logTp the value for AIP_LOGS.LOG_TP
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setLogTp(String logTp) {
        this.logTp = logTp == null ? null : logTp.trim();
    }

    /**
     */
    public String getLogStr() {
        return logStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_LOGS.LOG_STR
     *
     * @param logStr the value for AIP_LOGS.LOG_STR
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setLogStr(String logStr) {
        this.logStr = logStr == null ? null : logStr.trim();
    }

    /**
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_LOGS.USER_ID
     *
     * @param userId the value for AIP_LOGS.USER_ID
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     */
    public String getLogDetail() {
        return logDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_LOGS.LOG_DETAIL
     *
     * @param logDetail the value for AIP_LOGS.LOG_DETAIL
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setLogDetail(String logDetail) {
        this.logDetail = logDetail == null ? null : logDetail.trim();
    }

    /**
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_LOGS.REG_DT
     *
     * @param regDt the value for AIP_LOGS.REG_DT
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_LOGS.MOD_DT
     *
     * @param modDt the value for AIP_LOGS.MOD_DT
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }
}