package com.nomad.data.agent.domain.dao.common;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AIP_SERVER
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 14 15:21:16 KST 2020
 */
public class AipServerKey {
    /**
     */
    private String serverId;

    /**
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_SERVER.SERVER_ID
     *
     * @param serverId the value for AIP_SERVER.SERVER_ID
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    public void setServerId(String serverId) {
        this.serverId = serverId == null ? null : serverId.trim();
    }
}