package com.nomad.data.agent.domain.dao.common;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AIP_USER
 *
 * @mbg.generated do_not_delete_during_merge Thu Apr 09 11:36:59 KST 2020
 */
public class AipUserKey {
    /**
     */
    private String userId;

    /**
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_USER.USER_ID
     *
     * @param userId the value for AIP_USER.USER_ID
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}