package com.nomad.data.agent.domain.dao.common;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AipUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public AipUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNmIsNull() {
            addCriterion("USER_NM is null");
            return (Criteria) this;
        }

        public Criteria andUserNmIsNotNull() {
            addCriterion("USER_NM is not null");
            return (Criteria) this;
        }

        public Criteria andUserNmEqualTo(String value) {
            addCriterion("USER_NM =", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotEqualTo(String value) {
            addCriterion("USER_NM <>", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmGreaterThan(String value) {
            addCriterion("USER_NM >", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NM >=", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLessThan(String value) {
            addCriterion("USER_NM <", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLessThanOrEqualTo(String value) {
            addCriterion("USER_NM <=", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmLike(String value) {
            addCriterion("USER_NM like", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotLike(String value) {
            addCriterion("USER_NM not like", value, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmIn(List<String> values) {
            addCriterion("USER_NM in", values, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotIn(List<String> values) {
            addCriterion("USER_NM not in", values, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmBetween(String value1, String value2) {
            addCriterion("USER_NM between", value1, value2, "userNm");
            return (Criteria) this;
        }

        public Criteria andUserNmNotBetween(String value1, String value2) {
            addCriterion("USER_NM not between", value1, value2, "userNm");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNull() {
            addCriterion("BANK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("BANK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(String value) {
            addCriterion("BANK_ID =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(String value) {
            addCriterion("BANK_ID <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(String value) {
            addCriterion("BANK_ID >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_ID >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(String value) {
            addCriterion("BANK_ID <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(String value) {
            addCriterion("BANK_ID <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLike(String value) {
            addCriterion("BANK_ID like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotLike(String value) {
            addCriterion("BANK_ID not like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<String> values) {
            addCriterion("BANK_ID in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<String> values) {
            addCriterion("BANK_ID not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(String value1, String value2) {
            addCriterion("BANK_ID between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(String value1, String value2) {
            addCriterion("BANK_ID not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andDeptIsNull() {
            addCriterion("DEPT is null");
            return (Criteria) this;
        }

        public Criteria andDeptIsNotNull() {
            addCriterion("DEPT is not null");
            return (Criteria) this;
        }

        public Criteria andDeptEqualTo(String value) {
            addCriterion("DEPT =", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptNotEqualTo(String value) {
            addCriterion("DEPT <>", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptGreaterThan(String value) {
            addCriterion("DEPT >", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT >=", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptLessThan(String value) {
            addCriterion("DEPT <", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptLessThanOrEqualTo(String value) {
            addCriterion("DEPT <=", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptLike(String value) {
            addCriterion("DEPT like", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptNotLike(String value) {
            addCriterion("DEPT not like", value, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptIn(List<String> values) {
            addCriterion("DEPT in", values, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptNotIn(List<String> values) {
            addCriterion("DEPT not in", values, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptBetween(String value1, String value2) {
            addCriterion("DEPT between", value1, value2, "dept");
            return (Criteria) this;
        }

        public Criteria andDeptNotBetween(String value1, String value2) {
            addCriterion("DEPT not between", value1, value2, "dept");
            return (Criteria) this;
        }

        public Criteria andGitUserNmIsNull() {
            addCriterion("GIT_USER_NM is null");
            return (Criteria) this;
        }

        public Criteria andGitUserNmIsNotNull() {
            addCriterion("GIT_USER_NM is not null");
            return (Criteria) this;
        }

        public Criteria andGitUserNmEqualTo(String value) {
            addCriterion("GIT_USER_NM =", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmNotEqualTo(String value) {
            addCriterion("GIT_USER_NM <>", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmGreaterThan(String value) {
            addCriterion("GIT_USER_NM >", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("GIT_USER_NM >=", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmLessThan(String value) {
            addCriterion("GIT_USER_NM <", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmLessThanOrEqualTo(String value) {
            addCriterion("GIT_USER_NM <=", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmLike(String value) {
            addCriterion("GIT_USER_NM like", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmNotLike(String value) {
            addCriterion("GIT_USER_NM not like", value, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmIn(List<String> values) {
            addCriterion("GIT_USER_NM in", values, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmNotIn(List<String> values) {
            addCriterion("GIT_USER_NM not in", values, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmBetween(String value1, String value2) {
            addCriterion("GIT_USER_NM between", value1, value2, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitUserNmNotBetween(String value1, String value2) {
            addCriterion("GIT_USER_NM not between", value1, value2, "gitUserNm");
            return (Criteria) this;
        }

        public Criteria andGitEmailIsNull() {
            addCriterion("GIT_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andGitEmailIsNotNull() {
            addCriterion("GIT_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andGitEmailEqualTo(String value) {
            addCriterion("GIT_EMAIL =", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailNotEqualTo(String value) {
            addCriterion("GIT_EMAIL <>", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailGreaterThan(String value) {
            addCriterion("GIT_EMAIL >", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailGreaterThanOrEqualTo(String value) {
            addCriterion("GIT_EMAIL >=", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailLessThan(String value) {
            addCriterion("GIT_EMAIL <", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailLessThanOrEqualTo(String value) {
            addCriterion("GIT_EMAIL <=", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailLike(String value) {
            addCriterion("GIT_EMAIL like", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailNotLike(String value) {
            addCriterion("GIT_EMAIL not like", value, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailIn(List<String> values) {
            addCriterion("GIT_EMAIL in", values, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailNotIn(List<String> values) {
            addCriterion("GIT_EMAIL not in", values, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailBetween(String value1, String value2) {
            addCriterion("GIT_EMAIL between", value1, value2, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andGitEmailNotBetween(String value1, String value2) {
            addCriterion("GIT_EMAIL not between", value1, value2, "gitEmail");
            return (Criteria) this;
        }

        public Criteria andPswdIsNull() {
            addCriterion("PSWD is null");
            return (Criteria) this;
        }

        public Criteria andPswdIsNotNull() {
            addCriterion("PSWD is not null");
            return (Criteria) this;
        }

        public Criteria andPswdEqualTo(String value) {
            addCriterion("PSWD =", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdNotEqualTo(String value) {
            addCriterion("PSWD <>", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdGreaterThan(String value) {
            addCriterion("PSWD >", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdGreaterThanOrEqualTo(String value) {
            addCriterion("PSWD >=", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdLessThan(String value) {
            addCriterion("PSWD <", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdLessThanOrEqualTo(String value) {
            addCriterion("PSWD <=", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdLike(String value) {
            addCriterion("PSWD like", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdNotLike(String value) {
            addCriterion("PSWD not like", value, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdIn(List<String> values) {
            addCriterion("PSWD in", values, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdNotIn(List<String> values) {
            addCriterion("PSWD not in", values, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdBetween(String value1, String value2) {
            addCriterion("PSWD between", value1, value2, "pswd");
            return (Criteria) this;
        }

        public Criteria andPswdNotBetween(String value1, String value2) {
            addCriterion("PSWD not between", value1, value2, "pswd");
            return (Criteria) this;
        }

        public Criteria andGitTokenIsNull() {
            addCriterion("GIT_TOKEN is null");
            return (Criteria) this;
        }

        public Criteria andGitTokenIsNotNull() {
            addCriterion("GIT_TOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andGitTokenEqualTo(String value) {
            addCriterion("GIT_TOKEN =", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenNotEqualTo(String value) {
            addCriterion("GIT_TOKEN <>", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenGreaterThan(String value) {
            addCriterion("GIT_TOKEN >", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenGreaterThanOrEqualTo(String value) {
            addCriterion("GIT_TOKEN >=", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenLessThan(String value) {
            addCriterion("GIT_TOKEN <", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenLessThanOrEqualTo(String value) {
            addCriterion("GIT_TOKEN <=", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenLike(String value) {
            addCriterion("GIT_TOKEN like", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenNotLike(String value) {
            addCriterion("GIT_TOKEN not like", value, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenIn(List<String> values) {
            addCriterion("GIT_TOKEN in", values, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenNotIn(List<String> values) {
            addCriterion("GIT_TOKEN not in", values, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenBetween(String value1, String value2) {
            addCriterion("GIT_TOKEN between", value1, value2, "gitToken");
            return (Criteria) this;
        }

        public Criteria andGitTokenNotBetween(String value1, String value2) {
            addCriterion("GIT_TOKEN not between", value1, value2, "gitToken");
            return (Criteria) this;
        }

        public Criteria andUserLvIsNull() {
            addCriterion("USER_LV is null");
            return (Criteria) this;
        }

        public Criteria andUserLvIsNotNull() {
            addCriterion("USER_LV is not null");
            return (Criteria) this;
        }

        public Criteria andUserLvEqualTo(Integer value) {
            addCriterion("USER_LV =", value, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvNotEqualTo(Integer value) {
            addCriterion("USER_LV <>", value, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvGreaterThan(Integer value) {
            addCriterion("USER_LV >", value, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_LV >=", value, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvLessThan(Integer value) {
            addCriterion("USER_LV <", value, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvLessThanOrEqualTo(Integer value) {
            addCriterion("USER_LV <=", value, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvIn(List<Integer> values) {
            addCriterion("USER_LV in", values, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvNotIn(List<Integer> values) {
            addCriterion("USER_LV not in", values, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvBetween(Integer value1, Integer value2) {
            addCriterion("USER_LV between", value1, value2, "userLv");
            return (Criteria) this;
        }

        public Criteria andUserLvNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_LV not between", value1, value2, "userLv");
            return (Criteria) this;
        }

        public Criteria andAccAuthIsNull() {
            addCriterion("ACC_AUTH is null");
            return (Criteria) this;
        }

        public Criteria andAccAuthIsNotNull() {
            addCriterion("ACC_AUTH is not null");
            return (Criteria) this;
        }

        public Criteria andAccAuthEqualTo(Integer value) {
            addCriterion("ACC_AUTH =", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthNotEqualTo(Integer value) {
            addCriterion("ACC_AUTH <>", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthGreaterThan(Integer value) {
            addCriterion("ACC_AUTH >", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACC_AUTH >=", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthLessThan(Integer value) {
            addCriterion("ACC_AUTH <", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthLessThanOrEqualTo(Integer value) {
            addCriterion("ACC_AUTH <=", value, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthIn(List<Integer> values) {
            addCriterion("ACC_AUTH in", values, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthNotIn(List<Integer> values) {
            addCriterion("ACC_AUTH not in", values, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthBetween(Integer value1, Integer value2) {
            addCriterion("ACC_AUTH between", value1, value2, "accAuth");
            return (Criteria) this;
        }

        public Criteria andAccAuthNotBetween(Integer value1, Integer value2) {
            addCriterion("ACC_AUTH not between", value1, value2, "accAuth");
            return (Criteria) this;
        }

        public Criteria andSnupStsIsNull() {
            addCriterion("SNUP_STS is null");
            return (Criteria) this;
        }

        public Criteria andSnupStsIsNotNull() {
            addCriterion("SNUP_STS is not null");
            return (Criteria) this;
        }

        public Criteria andSnupStsEqualTo(String value) {
            addCriterion("SNUP_STS =", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsNotEqualTo(String value) {
            addCriterion("SNUP_STS <>", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsGreaterThan(String value) {
            addCriterion("SNUP_STS >", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsGreaterThanOrEqualTo(String value) {
            addCriterion("SNUP_STS >=", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsLessThan(String value) {
            addCriterion("SNUP_STS <", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsLessThanOrEqualTo(String value) {
            addCriterion("SNUP_STS <=", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsLike(String value) {
            addCriterion("SNUP_STS like", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsNotLike(String value) {
            addCriterion("SNUP_STS not like", value, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsIn(List<String> values) {
            addCriterion("SNUP_STS in", values, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsNotIn(List<String> values) {
            addCriterion("SNUP_STS not in", values, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsBetween(String value1, String value2) {
            addCriterion("SNUP_STS between", value1, value2, "snupSts");
            return (Criteria) this;
        }

        public Criteria andSnupStsNotBetween(String value1, String value2) {
            addCriterion("SNUP_STS not between", value1, value2, "snupSts");
            return (Criteria) this;
        }

        public Criteria andTknIsNull() {
            addCriterion("TKN is null");
            return (Criteria) this;
        }

        public Criteria andTknIsNotNull() {
            addCriterion("TKN is not null");
            return (Criteria) this;
        }

        public Criteria andTknEqualTo(String value) {
            addCriterion("TKN =", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknNotEqualTo(String value) {
            addCriterion("TKN <>", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknGreaterThan(String value) {
            addCriterion("TKN >", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknGreaterThanOrEqualTo(String value) {
            addCriterion("TKN >=", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknLessThan(String value) {
            addCriterion("TKN <", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknLessThanOrEqualTo(String value) {
            addCriterion("TKN <=", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknLike(String value) {
            addCriterion("TKN like", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknNotLike(String value) {
            addCriterion("TKN not like", value, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknIn(List<String> values) {
            addCriterion("TKN in", values, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknNotIn(List<String> values) {
            addCriterion("TKN not in", values, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknBetween(String value1, String value2) {
            addCriterion("TKN between", value1, value2, "tkn");
            return (Criteria) this;
        }

        public Criteria andTknNotBetween(String value1, String value2) {
            addCriterion("TKN not between", value1, value2, "tkn");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNull() {
            addCriterion("REG_DT is null");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNotNull() {
            addCriterion("REG_DT is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtEqualTo(Date value) {
            addCriterion("REG_DT =", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotEqualTo(Date value) {
            addCriterion("REG_DT <>", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThan(Date value) {
            addCriterion("REG_DT >", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DT >=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThan(Date value) {
            addCriterion("REG_DT <", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThanOrEqualTo(Date value) {
            addCriterion("REG_DT <=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtIn(List<Date> values) {
            addCriterion("REG_DT in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotIn(List<Date> values) {
            addCriterion("REG_DT not in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtBetween(Date value1, Date value2) {
            addCriterion("REG_DT between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotBetween(Date value1, Date value2) {
            addCriterion("REG_DT not between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andModDtIsNull() {
            addCriterion("MOD_DT is null");
            return (Criteria) this;
        }

        public Criteria andModDtIsNotNull() {
            addCriterion("MOD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andModDtEqualTo(Date value) {
            addCriterion("MOD_DT =", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotEqualTo(Date value) {
            addCriterion("MOD_DT <>", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThan(Date value) {
            addCriterion("MOD_DT >", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DT >=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThan(Date value) {
            addCriterion("MOD_DT <", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DT <=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtIn(List<Date> values) {
            addCriterion("MOD_DT in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotIn(List<Date> values) {
            addCriterion("MOD_DT not in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtBetween(Date value1, Date value2) {
            addCriterion("MOD_DT between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DT not between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andGitPswdIsNull() {
            addCriterion("GIT_PSWD is null");
            return (Criteria) this;
        }

        public Criteria andGitPswdIsNotNull() {
            addCriterion("GIT_PSWD is not null");
            return (Criteria) this;
        }

        public Criteria andGitPswdEqualTo(BigDecimal value) {
            addCriterion("GIT_PSWD =", value, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdNotEqualTo(BigDecimal value) {
            addCriterion("GIT_PSWD <>", value, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdGreaterThan(BigDecimal value) {
            addCriterion("GIT_PSWD >", value, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GIT_PSWD >=", value, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdLessThan(BigDecimal value) {
            addCriterion("GIT_PSWD <", value, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GIT_PSWD <=", value, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdIn(List<BigDecimal> values) {
            addCriterion("GIT_PSWD in", values, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdNotIn(List<BigDecimal> values) {
            addCriterion("GIT_PSWD not in", values, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GIT_PSWD between", value1, value2, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andGitPswdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GIT_PSWD not between", value1, value2, "gitPswd");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("IP in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("IP not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_USER
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 09 11:36:59 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}