package com.nomad.data.agent.domain.dao.common;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AipWorkspaceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public AipWorkspaceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWkspcIdIsNull() {
            addCriterion("WKSPC_ID is null");
            return (Criteria) this;
        }

        public Criteria andWkspcIdIsNotNull() {
            addCriterion("WKSPC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWkspcIdEqualTo(String value) {
            addCriterion("WKSPC_ID =", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdNotEqualTo(String value) {
            addCriterion("WKSPC_ID <>", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdGreaterThan(String value) {
            addCriterion("WKSPC_ID >", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdGreaterThanOrEqualTo(String value) {
            addCriterion("WKSPC_ID >=", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdLessThan(String value) {
            addCriterion("WKSPC_ID <", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdLessThanOrEqualTo(String value) {
            addCriterion("WKSPC_ID <=", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdLike(String value) {
            addCriterion("WKSPC_ID like", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdNotLike(String value) {
            addCriterion("WKSPC_ID not like", value, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdIn(List<String> values) {
            addCriterion("WKSPC_ID in", values, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdNotIn(List<String> values) {
            addCriterion("WKSPC_ID not in", values, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdBetween(String value1, String value2) {
            addCriterion("WKSPC_ID between", value1, value2, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcIdNotBetween(String value1, String value2) {
            addCriterion("WKSPC_ID not between", value1, value2, "wkspcId");
            return (Criteria) this;
        }

        public Criteria andWkspcNmIsNull() {
            addCriterion("WKSPC_NM is null");
            return (Criteria) this;
        }

        public Criteria andWkspcNmIsNotNull() {
            addCriterion("WKSPC_NM is not null");
            return (Criteria) this;
        }

        public Criteria andWkspcNmEqualTo(String value) {
            addCriterion("WKSPC_NM =", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmNotEqualTo(String value) {
            addCriterion("WKSPC_NM <>", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmGreaterThan(String value) {
            addCriterion("WKSPC_NM >", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmGreaterThanOrEqualTo(String value) {
            addCriterion("WKSPC_NM >=", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmLessThan(String value) {
            addCriterion("WKSPC_NM <", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmLessThanOrEqualTo(String value) {
            addCriterion("WKSPC_NM <=", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmLike(String value) {
            addCriterion("WKSPC_NM like", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmNotLike(String value) {
            addCriterion("WKSPC_NM not like", value, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmIn(List<String> values) {
            addCriterion("WKSPC_NM in", values, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmNotIn(List<String> values) {
            addCriterion("WKSPC_NM not in", values, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmBetween(String value1, String value2) {
            addCriterion("WKSPC_NM between", value1, value2, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcNmNotBetween(String value1, String value2) {
            addCriterion("WKSPC_NM not between", value1, value2, "wkspcNm");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpIsNull() {
            addCriterion("WKSPC_USE_TP is null");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpIsNotNull() {
            addCriterion("WKSPC_USE_TP is not null");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpEqualTo(String value) {
            addCriterion("WKSPC_USE_TP =", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpNotEqualTo(String value) {
            addCriterion("WKSPC_USE_TP <>", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpGreaterThan(String value) {
            addCriterion("WKSPC_USE_TP >", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpGreaterThanOrEqualTo(String value) {
            addCriterion("WKSPC_USE_TP >=", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpLessThan(String value) {
            addCriterion("WKSPC_USE_TP <", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpLessThanOrEqualTo(String value) {
            addCriterion("WKSPC_USE_TP <=", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpLike(String value) {
            addCriterion("WKSPC_USE_TP like", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpNotLike(String value) {
            addCriterion("WKSPC_USE_TP not like", value, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpIn(List<String> values) {
            addCriterion("WKSPC_USE_TP in", values, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpNotIn(List<String> values) {
            addCriterion("WKSPC_USE_TP not in", values, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpBetween(String value1, String value2) {
            addCriterion("WKSPC_USE_TP between", value1, value2, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcUseTpNotBetween(String value1, String value2) {
            addCriterion("WKSPC_USE_TP not between", value1, value2, "wkspcUseTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpIsNull() {
            addCriterion("WKSPC_SZ_TP is null");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpIsNotNull() {
            addCriterion("WKSPC_SZ_TP is not null");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpEqualTo(String value) {
            addCriterion("WKSPC_SZ_TP =", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpNotEqualTo(String value) {
            addCriterion("WKSPC_SZ_TP <>", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpGreaterThan(String value) {
            addCriterion("WKSPC_SZ_TP >", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpGreaterThanOrEqualTo(String value) {
            addCriterion("WKSPC_SZ_TP >=", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpLessThan(String value) {
            addCriterion("WKSPC_SZ_TP <", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpLessThanOrEqualTo(String value) {
            addCriterion("WKSPC_SZ_TP <=", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpLike(String value) {
            addCriterion("WKSPC_SZ_TP like", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpNotLike(String value) {
            addCriterion("WKSPC_SZ_TP not like", value, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpIn(List<String> values) {
            addCriterion("WKSPC_SZ_TP in", values, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpNotIn(List<String> values) {
            addCriterion("WKSPC_SZ_TP not in", values, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpBetween(String value1, String value2) {
            addCriterion("WKSPC_SZ_TP between", value1, value2, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andWkspcSzTpNotBetween(String value1, String value2) {
            addCriterion("WKSPC_SZ_TP not between", value1, value2, "wkspcSzTp");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNull() {
            addCriterion("SERVER_ID is null");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNotNull() {
            addCriterion("SERVER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andServerIdEqualTo(String value) {
            addCriterion("SERVER_ID =", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotEqualTo(String value) {
            addCriterion("SERVER_ID <>", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThan(String value) {
            addCriterion("SERVER_ID >", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThanOrEqualTo(String value) {
            addCriterion("SERVER_ID >=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThan(String value) {
            addCriterion("SERVER_ID <", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThanOrEqualTo(String value) {
            addCriterion("SERVER_ID <=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLike(String value) {
            addCriterion("SERVER_ID like", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotLike(String value) {
            addCriterion("SERVER_ID not like", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdIn(List<String> values) {
            addCriterion("SERVER_ID in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotIn(List<String> values) {
            addCriterion("SERVER_ID not in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdBetween(String value1, String value2) {
            addCriterion("SERVER_ID between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotBetween(String value1, String value2) {
            addCriterion("SERVER_ID not between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andImgIdIsNull() {
            addCriterion("IMG_ID is null");
            return (Criteria) this;
        }

        public Criteria andImgIdIsNotNull() {
            addCriterion("IMG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andImgIdEqualTo(String value) {
            addCriterion("IMG_ID =", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotEqualTo(String value) {
            addCriterion("IMG_ID <>", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdGreaterThan(String value) {
            addCriterion("IMG_ID >", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdGreaterThanOrEqualTo(String value) {
            addCriterion("IMG_ID >=", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLessThan(String value) {
            addCriterion("IMG_ID <", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLessThanOrEqualTo(String value) {
            addCriterion("IMG_ID <=", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLike(String value) {
            addCriterion("IMG_ID like", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotLike(String value) {
            addCriterion("IMG_ID not like", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdIn(List<String> values) {
            addCriterion("IMG_ID in", values, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotIn(List<String> values) {
            addCriterion("IMG_ID not in", values, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdBetween(String value1, String value2) {
            addCriterion("IMG_ID between", value1, value2, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotBetween(String value1, String value2) {
            addCriterion("IMG_ID not between", value1, value2, "imgId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdIsNull() {
            addCriterion("DKR_CTNR_ID is null");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdIsNotNull() {
            addCriterion("DKR_CTNR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdEqualTo(String value) {
            addCriterion("DKR_CTNR_ID =", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdNotEqualTo(String value) {
            addCriterion("DKR_CTNR_ID <>", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdGreaterThan(String value) {
            addCriterion("DKR_CTNR_ID >", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdGreaterThanOrEqualTo(String value) {
            addCriterion("DKR_CTNR_ID >=", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdLessThan(String value) {
            addCriterion("DKR_CTNR_ID <", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdLessThanOrEqualTo(String value) {
            addCriterion("DKR_CTNR_ID <=", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdLike(String value) {
            addCriterion("DKR_CTNR_ID like", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdNotLike(String value) {
            addCriterion("DKR_CTNR_ID not like", value, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdIn(List<String> values) {
            addCriterion("DKR_CTNR_ID in", values, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdNotIn(List<String> values) {
            addCriterion("DKR_CTNR_ID not in", values, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdBetween(String value1, String value2) {
            addCriterion("DKR_CTNR_ID between", value1, value2, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andDkrCtnrIdNotBetween(String value1, String value2) {
            addCriterion("DKR_CTNR_ID not between", value1, value2, "dkrCtnrId");
            return (Criteria) this;
        }

        public Criteria andWorkStsIsNull() {
            addCriterion("WORK_STS is null");
            return (Criteria) this;
        }

        public Criteria andWorkStsIsNotNull() {
            addCriterion("WORK_STS is not null");
            return (Criteria) this;
        }

        public Criteria andWorkStsEqualTo(String value) {
            addCriterion("WORK_STS =", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsNotEqualTo(String value) {
            addCriterion("WORK_STS <>", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsGreaterThan(String value) {
            addCriterion("WORK_STS >", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_STS >=", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsLessThan(String value) {
            addCriterion("WORK_STS <", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsLessThanOrEqualTo(String value) {
            addCriterion("WORK_STS <=", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsLike(String value) {
            addCriterion("WORK_STS like", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsNotLike(String value) {
            addCriterion("WORK_STS not like", value, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsIn(List<String> values) {
            addCriterion("WORK_STS in", values, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsNotIn(List<String> values) {
            addCriterion("WORK_STS not in", values, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsBetween(String value1, String value2) {
            addCriterion("WORK_STS between", value1, value2, "workSts");
            return (Criteria) this;
        }

        public Criteria andWorkStsNotBetween(String value1, String value2) {
            addCriterion("WORK_STS not between", value1, value2, "workSts");
            return (Criteria) this;
        }

        public Criteria andLibTpIsNull() {
            addCriterion("LIB_TP is null");
            return (Criteria) this;
        }

        public Criteria andLibTpIsNotNull() {
            addCriterion("LIB_TP is not null");
            return (Criteria) this;
        }

        public Criteria andLibTpEqualTo(String value) {
            addCriterion("LIB_TP =", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpNotEqualTo(String value) {
            addCriterion("LIB_TP <>", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpGreaterThan(String value) {
            addCriterion("LIB_TP >", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpGreaterThanOrEqualTo(String value) {
            addCriterion("LIB_TP >=", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpLessThan(String value) {
            addCriterion("LIB_TP <", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpLessThanOrEqualTo(String value) {
            addCriterion("LIB_TP <=", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpLike(String value) {
            addCriterion("LIB_TP like", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpNotLike(String value) {
            addCriterion("LIB_TP not like", value, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpIn(List<String> values) {
            addCriterion("LIB_TP in", values, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpNotIn(List<String> values) {
            addCriterion("LIB_TP not in", values, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpBetween(String value1, String value2) {
            addCriterion("LIB_TP between", value1, value2, "libTp");
            return (Criteria) this;
        }

        public Criteria andLibTpNotBetween(String value1, String value2) {
            addCriterion("LIB_TP not between", value1, value2, "libTp");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("OWNER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("OWNER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(String value) {
            addCriterion("OWNER_ID =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(String value) {
            addCriterion("OWNER_ID <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(String value) {
            addCriterion("OWNER_ID >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER_ID >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(String value) {
            addCriterion("OWNER_ID <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("OWNER_ID <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLike(String value) {
            addCriterion("OWNER_ID like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotLike(String value) {
            addCriterion("OWNER_ID not like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<String> values) {
            addCriterion("OWNER_ID in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<String> values) {
            addCriterion("OWNER_ID not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(String value1, String value2) {
            addCriterion("OWNER_ID between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(String value1, String value2) {
            addCriterion("OWNER_ID not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumIsNull() {
            addCriterion("ASGND_CPU_NUM is null");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumIsNotNull() {
            addCriterion("ASGND_CPU_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumEqualTo(BigDecimal value) {
            addCriterion("ASGND_CPU_NUM =", value, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumNotEqualTo(BigDecimal value) {
            addCriterion("ASGND_CPU_NUM <>", value, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumGreaterThan(BigDecimal value) {
            addCriterion("ASGND_CPU_NUM >", value, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_CPU_NUM >=", value, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumLessThan(BigDecimal value) {
            addCriterion("ASGND_CPU_NUM <", value, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_CPU_NUM <=", value, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumIn(List<BigDecimal> values) {
            addCriterion("ASGND_CPU_NUM in", values, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumNotIn(List<BigDecimal> values) {
            addCriterion("ASGND_CPU_NUM not in", values, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_CPU_NUM between", value1, value2, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndCpuNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_CPU_NUM not between", value1, value2, "asgndCpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumIsNull() {
            addCriterion("ASGND_GPU_NUM is null");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumIsNotNull() {
            addCriterion("ASGND_GPU_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumEqualTo(BigDecimal value) {
            addCriterion("ASGND_GPU_NUM =", value, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumNotEqualTo(BigDecimal value) {
            addCriterion("ASGND_GPU_NUM <>", value, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumGreaterThan(BigDecimal value) {
            addCriterion("ASGND_GPU_NUM >", value, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_GPU_NUM >=", value, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumLessThan(BigDecimal value) {
            addCriterion("ASGND_GPU_NUM <", value, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_GPU_NUM <=", value, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumIn(List<BigDecimal> values) {
            addCriterion("ASGND_GPU_NUM in", values, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumNotIn(List<BigDecimal> values) {
            addCriterion("ASGND_GPU_NUM not in", values, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_GPU_NUM between", value1, value2, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndGpuNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_GPU_NUM not between", value1, value2, "asgndGpuNum");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzIsNull() {
            addCriterion("ASGND_DIS_SZ is null");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzIsNotNull() {
            addCriterion("ASGND_DIS_SZ is not null");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzEqualTo(BigDecimal value) {
            addCriterion("ASGND_DIS_SZ =", value, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzNotEqualTo(BigDecimal value) {
            addCriterion("ASGND_DIS_SZ <>", value, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzGreaterThan(BigDecimal value) {
            addCriterion("ASGND_DIS_SZ >", value, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_DIS_SZ >=", value, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzLessThan(BigDecimal value) {
            addCriterion("ASGND_DIS_SZ <", value, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_DIS_SZ <=", value, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzIn(List<BigDecimal> values) {
            addCriterion("ASGND_DIS_SZ in", values, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzNotIn(List<BigDecimal> values) {
            addCriterion("ASGND_DIS_SZ not in", values, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_DIS_SZ between", value1, value2, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndDisSzNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_DIS_SZ not between", value1, value2, "asgndDisSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzIsNull() {
            addCriterion("ASGND_MEM_SZ is null");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzIsNotNull() {
            addCriterion("ASGND_MEM_SZ is not null");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzEqualTo(BigDecimal value) {
            addCriterion("ASGND_MEM_SZ =", value, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzNotEqualTo(BigDecimal value) {
            addCriterion("ASGND_MEM_SZ <>", value, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzGreaterThan(BigDecimal value) {
            addCriterion("ASGND_MEM_SZ >", value, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_MEM_SZ >=", value, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzLessThan(BigDecimal value) {
            addCriterion("ASGND_MEM_SZ <", value, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ASGND_MEM_SZ <=", value, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzIn(List<BigDecimal> values) {
            addCriterion("ASGND_MEM_SZ in", values, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzNotIn(List<BigDecimal> values) {
            addCriterion("ASGND_MEM_SZ not in", values, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_MEM_SZ between", value1, value2, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andAsgndMemSzNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ASGND_MEM_SZ not between", value1, value2, "asgndMemSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzIsNull() {
            addCriterion("UPLD_DATA_SZ is null");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzIsNotNull() {
            addCriterion("UPLD_DATA_SZ is not null");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzEqualTo(BigDecimal value) {
            addCriterion("UPLD_DATA_SZ =", value, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzNotEqualTo(BigDecimal value) {
            addCriterion("UPLD_DATA_SZ <>", value, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzGreaterThan(BigDecimal value) {
            addCriterion("UPLD_DATA_SZ >", value, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UPLD_DATA_SZ >=", value, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzLessThan(BigDecimal value) {
            addCriterion("UPLD_DATA_SZ <", value, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UPLD_DATA_SZ <=", value, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzIn(List<BigDecimal> values) {
            addCriterion("UPLD_DATA_SZ in", values, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzNotIn(List<BigDecimal> values) {
            addCriterion("UPLD_DATA_SZ not in", values, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPLD_DATA_SZ between", value1, value2, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andUpldDataSzNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPLD_DATA_SZ not between", value1, value2, "upldDataSz");
            return (Criteria) this;
        }

        public Criteria andWkspcDescIsNull() {
            addCriterion("WKSPC_DESC is null");
            return (Criteria) this;
        }

        public Criteria andWkspcDescIsNotNull() {
            addCriterion("WKSPC_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andWkspcDescEqualTo(String value) {
            addCriterion("WKSPC_DESC =", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescNotEqualTo(String value) {
            addCriterion("WKSPC_DESC <>", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescGreaterThan(String value) {
            addCriterion("WKSPC_DESC >", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescGreaterThanOrEqualTo(String value) {
            addCriterion("WKSPC_DESC >=", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescLessThan(String value) {
            addCriterion("WKSPC_DESC <", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescLessThanOrEqualTo(String value) {
            addCriterion("WKSPC_DESC <=", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescLike(String value) {
            addCriterion("WKSPC_DESC like", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescNotLike(String value) {
            addCriterion("WKSPC_DESC not like", value, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescIn(List<String> values) {
            addCriterion("WKSPC_DESC in", values, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescNotIn(List<String> values) {
            addCriterion("WKSPC_DESC not in", values, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescBetween(String value1, String value2) {
            addCriterion("WKSPC_DESC between", value1, value2, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andWkspcDescNotBetween(String value1, String value2) {
            addCriterion("WKSPC_DESC not between", value1, value2, "wkspcDesc");
            return (Criteria) this;
        }

        public Criteria andGitRepoIsNull() {
            addCriterion("GIT_REPO is null");
            return (Criteria) this;
        }

        public Criteria andGitRepoIsNotNull() {
            addCriterion("GIT_REPO is not null");
            return (Criteria) this;
        }

        public Criteria andGitRepoEqualTo(String value) {
            addCriterion("GIT_REPO =", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoNotEqualTo(String value) {
            addCriterion("GIT_REPO <>", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoGreaterThan(String value) {
            addCriterion("GIT_REPO >", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoGreaterThanOrEqualTo(String value) {
            addCriterion("GIT_REPO >=", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoLessThan(String value) {
            addCriterion("GIT_REPO <", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoLessThanOrEqualTo(String value) {
            addCriterion("GIT_REPO <=", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoLike(String value) {
            addCriterion("GIT_REPO like", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoNotLike(String value) {
            addCriterion("GIT_REPO not like", value, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoIn(List<String> values) {
            addCriterion("GIT_REPO in", values, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoNotIn(List<String> values) {
            addCriterion("GIT_REPO not in", values, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoBetween(String value1, String value2) {
            addCriterion("GIT_REPO between", value1, value2, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andGitRepoNotBetween(String value1, String value2) {
            addCriterion("GIT_REPO not between", value1, value2, "gitRepo");
            return (Criteria) this;
        }

        public Criteria andExptStDtIsNull() {
            addCriterion("EXPT_ST_DT is null");
            return (Criteria) this;
        }

        public Criteria andExptStDtIsNotNull() {
            addCriterion("EXPT_ST_DT is not null");
            return (Criteria) this;
        }

        public Criteria andExptStDtEqualTo(String value) {
            addCriterion("EXPT_ST_DT =", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotEqualTo(String value) {
            addCriterion("EXPT_ST_DT <>", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtGreaterThan(String value) {
            addCriterion("EXPT_ST_DT >", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtGreaterThanOrEqualTo(String value) {
            addCriterion("EXPT_ST_DT >=", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtLessThan(String value) {
            addCriterion("EXPT_ST_DT <", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtLessThanOrEqualTo(String value) {
            addCriterion("EXPT_ST_DT <=", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtLike(String value) {
            addCriterion("EXPT_ST_DT like", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotLike(String value) {
            addCriterion("EXPT_ST_DT not like", value, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtIn(List<String> values) {
            addCriterion("EXPT_ST_DT in", values, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotIn(List<String> values) {
            addCriterion("EXPT_ST_DT not in", values, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtBetween(String value1, String value2) {
            addCriterion("EXPT_ST_DT between", value1, value2, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptStDtNotBetween(String value1, String value2) {
            addCriterion("EXPT_ST_DT not between", value1, value2, "exptStDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtIsNull() {
            addCriterion("EXPT_ED_DT is null");
            return (Criteria) this;
        }

        public Criteria andExptEdDtIsNotNull() {
            addCriterion("EXPT_ED_DT is not null");
            return (Criteria) this;
        }

        public Criteria andExptEdDtEqualTo(String value) {
            addCriterion("EXPT_ED_DT =", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotEqualTo(String value) {
            addCriterion("EXPT_ED_DT <>", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtGreaterThan(String value) {
            addCriterion("EXPT_ED_DT >", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtGreaterThanOrEqualTo(String value) {
            addCriterion("EXPT_ED_DT >=", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtLessThan(String value) {
            addCriterion("EXPT_ED_DT <", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtLessThanOrEqualTo(String value) {
            addCriterion("EXPT_ED_DT <=", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtLike(String value) {
            addCriterion("EXPT_ED_DT like", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotLike(String value) {
            addCriterion("EXPT_ED_DT not like", value, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtIn(List<String> values) {
            addCriterion("EXPT_ED_DT in", values, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotIn(List<String> values) {
            addCriterion("EXPT_ED_DT not in", values, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtBetween(String value1, String value2) {
            addCriterion("EXPT_ED_DT between", value1, value2, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andExptEdDtNotBetween(String value1, String value2) {
            addCriterion("EXPT_ED_DT not between", value1, value2, "exptEdDt");
            return (Criteria) this;
        }

        public Criteria andDelFlIsNull() {
            addCriterion("DEL_FL is null");
            return (Criteria) this;
        }

        public Criteria andDelFlIsNotNull() {
            addCriterion("DEL_FL is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlEqualTo(String value) {
            addCriterion("DEL_FL =", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotEqualTo(String value) {
            addCriterion("DEL_FL <>", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlGreaterThan(String value) {
            addCriterion("DEL_FL >", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_FL >=", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLessThan(String value) {
            addCriterion("DEL_FL <", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLessThanOrEqualTo(String value) {
            addCriterion("DEL_FL <=", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlLike(String value) {
            addCriterion("DEL_FL like", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotLike(String value) {
            addCriterion("DEL_FL not like", value, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlIn(List<String> values) {
            addCriterion("DEL_FL in", values, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotIn(List<String> values) {
            addCriterion("DEL_FL not in", values, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlBetween(String value1, String value2) {
            addCriterion("DEL_FL between", value1, value2, "delFl");
            return (Criteria) this;
        }

        public Criteria andDelFlNotBetween(String value1, String value2) {
            addCriterion("DEL_FL not between", value1, value2, "delFl");
            return (Criteria) this;
        }

        public Criteria andProcessorIsNull() {
            addCriterion("PROCESSOR is null");
            return (Criteria) this;
        }

        public Criteria andProcessorIsNotNull() {
            addCriterion("PROCESSOR is not null");
            return (Criteria) this;
        }

        public Criteria andProcessorEqualTo(String value) {
            addCriterion("PROCESSOR =", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotEqualTo(String value) {
            addCriterion("PROCESSOR <>", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorGreaterThan(String value) {
            addCriterion("PROCESSOR >", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESSOR >=", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorLessThan(String value) {
            addCriterion("PROCESSOR <", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorLessThanOrEqualTo(String value) {
            addCriterion("PROCESSOR <=", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorLike(String value) {
            addCriterion("PROCESSOR like", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotLike(String value) {
            addCriterion("PROCESSOR not like", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorIn(List<String> values) {
            addCriterion("PROCESSOR in", values, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotIn(List<String> values) {
            addCriterion("PROCESSOR not in", values, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorBetween(String value1, String value2) {
            addCriterion("PROCESSOR between", value1, value2, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotBetween(String value1, String value2) {
            addCriterion("PROCESSOR not between", value1, value2, "processor");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("LANGUAGE is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("LANGUAGE is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("LANGUAGE =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("LANGUAGE <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("LANGUAGE >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("LANGUAGE >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("LANGUAGE <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("LANGUAGE <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("LANGUAGE like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("LANGUAGE not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("LANGUAGE in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("LANGUAGE not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("LANGUAGE between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("LANGUAGE not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlIsNull() {
            addCriterion("INCLUDE_PERSONAL_INFO_FL is null");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlIsNotNull() {
            addCriterion("INCLUDE_PERSONAL_INFO_FL is not null");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlEqualTo(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL =", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlNotEqualTo(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL <>", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlGreaterThan(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL >", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlGreaterThanOrEqualTo(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL >=", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlLessThan(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL <", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlLessThanOrEqualTo(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL <=", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlLike(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL like", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlNotLike(String value) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL not like", value, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlIn(List<String> values) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL in", values, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlNotIn(List<String> values) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL not in", values, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlBetween(String value1, String value2) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL between", value1, value2, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andIncludePersonalInfoFlNotBetween(String value1, String value2) {
            addCriterion("INCLUDE_PERSONAL_INFO_FL not between", value1, value2, "includePersonalInfoFl");
            return (Criteria) this;
        }

        public Criteria andReqMsgIsNull() {
            addCriterion("REQ_MSG is null");
            return (Criteria) this;
        }

        public Criteria andReqMsgIsNotNull() {
            addCriterion("REQ_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andReqMsgEqualTo(String value) {
            addCriterion("REQ_MSG =", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgNotEqualTo(String value) {
            addCriterion("REQ_MSG <>", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgGreaterThan(String value) {
            addCriterion("REQ_MSG >", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_MSG >=", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgLessThan(String value) {
            addCriterion("REQ_MSG <", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgLessThanOrEqualTo(String value) {
            addCriterion("REQ_MSG <=", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgLike(String value) {
            addCriterion("REQ_MSG like", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgNotLike(String value) {
            addCriterion("REQ_MSG not like", value, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgIn(List<String> values) {
            addCriterion("REQ_MSG in", values, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgNotIn(List<String> values) {
            addCriterion("REQ_MSG not in", values, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgBetween(String value1, String value2) {
            addCriterion("REQ_MSG between", value1, value2, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andReqMsgNotBetween(String value1, String value2) {
            addCriterion("REQ_MSG not between", value1, value2, "reqMsg");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNull() {
            addCriterion("REG_DT is null");
            return (Criteria) this;
        }

        public Criteria andRegDtIsNotNull() {
            addCriterion("REG_DT is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtEqualTo(Date value) {
            addCriterion("REG_DT =", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotEqualTo(Date value) {
            addCriterion("REG_DT <>", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThan(Date value) {
            addCriterion("REG_DT >", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DT >=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThan(Date value) {
            addCriterion("REG_DT <", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtLessThanOrEqualTo(Date value) {
            addCriterion("REG_DT <=", value, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtIn(List<Date> values) {
            addCriterion("REG_DT in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotIn(List<Date> values) {
            addCriterion("REG_DT not in", values, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtBetween(Date value1, Date value2) {
            addCriterion("REG_DT between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andRegDtNotBetween(Date value1, Date value2) {
            addCriterion("REG_DT not between", value1, value2, "regDt");
            return (Criteria) this;
        }

        public Criteria andModDtIsNull() {
            addCriterion("MOD_DT is null");
            return (Criteria) this;
        }

        public Criteria andModDtIsNotNull() {
            addCriterion("MOD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andModDtEqualTo(Date value) {
            addCriterion("MOD_DT =", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotEqualTo(Date value) {
            addCriterion("MOD_DT <>", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThan(Date value) {
            addCriterion("MOD_DT >", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DT >=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThan(Date value) {
            addCriterion("MOD_DT <", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DT <=", value, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtIn(List<Date> values) {
            addCriterion("MOD_DT in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotIn(List<Date> values) {
            addCriterion("MOD_DT not in", values, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtBetween(Date value1, Date value2) {
            addCriterion("MOD_DT between", value1, value2, "modDt");
            return (Criteria) this;
        }

        public Criteria andModDtNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DT not between", value1, value2, "modDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 29 14:31:25 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}