package com.nomad.data.agent.domain.dao.common;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AIP_WORKSPACE
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 29 14:31:25 KST 2020
 */
public class AipWorkspace extends AipWorkspaceKey {
    /**
     */
    private String wkspcNm;

    /**
     */
    private String wkspcUseTp;

    /**
     */
    private String wkspcSzTp;

    /**
     */
    private String serverId;

    /**
     */
    private String imgId;

    /**
     */
    private String dkrCtnrId;

    /**
     */
    private String workSts;

    /**
     */
    private String libTp;

    /**
     */
    private String ownerId;

    /**
     */
    private BigDecimal asgndCpuNum;

    /**
     */
    private BigDecimal asgndGpuNum;

    /**
     */
    private BigDecimal asgndDisSz;

    /**
     */
    private BigDecimal asgndMemSz;

    /**
     */
    private BigDecimal upldDataSz;

    /**
     */
    private String wkspcDesc;

    /**
     */
    private String gitRepo;

    /**
     */
    private String exptStDt;

    /**
     */
    private String exptEdDt;

    /**
     */
    private String delFl;

    /**
     */
    private String processor;

    /**
     */
    private String language;

    /**
     */
    private String includePersonalInfoFl;

    /**
     */
    private String reqMsg;

    /**
     */
    private Date regDt;

    /**
     */
    private Date modDt;

    /**
     */
    public String getWkspcNm() {
        return wkspcNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.WKSPC_NM
     *
     * @param wkspcNm the value for AIP_WORKSPACE.WKSPC_NM
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setWkspcNm(String wkspcNm) {
        this.wkspcNm = wkspcNm == null ? null : wkspcNm.trim();
    }

    /**
     */
    public String getWkspcUseTp() {
        return wkspcUseTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.WKSPC_USE_TP
     *
     * @param wkspcUseTp the value for AIP_WORKSPACE.WKSPC_USE_TP
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setWkspcUseTp(String wkspcUseTp) {
        this.wkspcUseTp = wkspcUseTp == null ? null : wkspcUseTp.trim();
    }

    /**
     */
    public String getWkspcSzTp() {
        return wkspcSzTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.WKSPC_SZ_TP
     *
     * @param wkspcSzTp the value for AIP_WORKSPACE.WKSPC_SZ_TP
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setWkspcSzTp(String wkspcSzTp) {
        this.wkspcSzTp = wkspcSzTp == null ? null : wkspcSzTp.trim();
    }

    /**
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.SERVER_ID
     *
     * @param serverId the value for AIP_WORKSPACE.SERVER_ID
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setServerId(String serverId) {
        this.serverId = serverId == null ? null : serverId.trim();
    }

    /**
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.IMG_ID
     *
     * @param imgId the value for AIP_WORKSPACE.IMG_ID
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setImgId(String imgId) {
        this.imgId = imgId == null ? null : imgId.trim();
    }

    /**
     */
    public String getDkrCtnrId() {
        return dkrCtnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.DKR_CTNR_ID
     *
     * @param dkrCtnrId the value for AIP_WORKSPACE.DKR_CTNR_ID
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setDkrCtnrId(String dkrCtnrId) {
        this.dkrCtnrId = dkrCtnrId == null ? null : dkrCtnrId.trim();
    }

    /**
     */
    public String getWorkSts() {
        return workSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.WORK_STS
     *
     * @param workSts the value for AIP_WORKSPACE.WORK_STS
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setWorkSts(String workSts) {
        this.workSts = workSts == null ? null : workSts.trim();
    }

    /**
     */
    public String getLibTp() {
        return libTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.LIB_TP
     *
     * @param libTp the value for AIP_WORKSPACE.LIB_TP
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setLibTp(String libTp) {
        this.libTp = libTp == null ? null : libTp.trim();
    }

    /**
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.OWNER_ID
     *
     * @param ownerId the value for AIP_WORKSPACE.OWNER_ID
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     */
    public BigDecimal getAsgndCpuNum() {
        return asgndCpuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.ASGND_CPU_NUM
     *
     * @param asgndCpuNum the value for AIP_WORKSPACE.ASGND_CPU_NUM
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setAsgndCpuNum(BigDecimal asgndCpuNum) {
        this.asgndCpuNum = asgndCpuNum;
    }

    /**
     */
    public BigDecimal getAsgndGpuNum() {
        return asgndGpuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.ASGND_GPU_NUM
     *
     * @param asgndGpuNum the value for AIP_WORKSPACE.ASGND_GPU_NUM
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setAsgndGpuNum(BigDecimal asgndGpuNum) {
        this.asgndGpuNum = asgndGpuNum;
    }

    /**
     */
    public BigDecimal getAsgndDisSz() {
        return asgndDisSz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.ASGND_DIS_SZ
     *
     * @param asgndDisSz the value for AIP_WORKSPACE.ASGND_DIS_SZ
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setAsgndDisSz(BigDecimal asgndDisSz) {
        this.asgndDisSz = asgndDisSz;
    }

    /**
     */
    public BigDecimal getAsgndMemSz() {
        return asgndMemSz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.ASGND_MEM_SZ
     *
     * @param asgndMemSz the value for AIP_WORKSPACE.ASGND_MEM_SZ
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setAsgndMemSz(BigDecimal asgndMemSz) {
        this.asgndMemSz = asgndMemSz;
    }

    /**
     */
    public BigDecimal getUpldDataSz() {
        return upldDataSz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.UPLD_DATA_SZ
     *
     * @param upldDataSz the value for AIP_WORKSPACE.UPLD_DATA_SZ
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setUpldDataSz(BigDecimal upldDataSz) {
        this.upldDataSz = upldDataSz;
    }

    /**
     */
    public String getWkspcDesc() {
        return wkspcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.WKSPC_DESC
     *
     * @param wkspcDesc the value for AIP_WORKSPACE.WKSPC_DESC
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setWkspcDesc(String wkspcDesc) {
        this.wkspcDesc = wkspcDesc == null ? null : wkspcDesc.trim();
    }

    /**
     */
    public String getGitRepo() {
        return gitRepo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.GIT_REPO
     *
     * @param gitRepo the value for AIP_WORKSPACE.GIT_REPO
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setGitRepo(String gitRepo) {
        this.gitRepo = gitRepo == null ? null : gitRepo.trim();
    }

    /**
     */
    public String getExptStDt() {
        return exptStDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.EXPT_ST_DT
     *
     * @param exptStDt the value for AIP_WORKSPACE.EXPT_ST_DT
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setExptStDt(String exptStDt) {
        this.exptStDt = exptStDt == null ? null : exptStDt.trim();
    }

    /**
     */
    public String getExptEdDt() {
        return exptEdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.EXPT_ED_DT
     *
     * @param exptEdDt the value for AIP_WORKSPACE.EXPT_ED_DT
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setExptEdDt(String exptEdDt) {
        this.exptEdDt = exptEdDt == null ? null : exptEdDt.trim();
    }

    /**
     */
    public String getDelFl() {
        return delFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.DEL_FL
     *
     * @param delFl the value for AIP_WORKSPACE.DEL_FL
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setDelFl(String delFl) {
        this.delFl = delFl == null ? null : delFl.trim();
    }

    /**
     */
    public String getProcessor() {
        return processor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.PROCESSOR
     *
     * @param processor the value for AIP_WORKSPACE.PROCESSOR
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setProcessor(String processor) {
        this.processor = processor == null ? null : processor.trim();
    }

    /**
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.LANGUAGE
     *
     * @param language the value for AIP_WORKSPACE.LANGUAGE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     */
    public String getIncludePersonalInfoFl() {
        return includePersonalInfoFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.INCLUDE_PERSONAL_INFO_FL
     *
     * @param includePersonalInfoFl the value for AIP_WORKSPACE.INCLUDE_PERSONAL_INFO_FL
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setIncludePersonalInfoFl(String includePersonalInfoFl) {
        this.includePersonalInfoFl = includePersonalInfoFl == null ? null : includePersonalInfoFl.trim();
    }

    /**
     */
    public String getReqMsg() {
        return reqMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.REQ_MSG
     *
     * @param reqMsg the value for AIP_WORKSPACE.REQ_MSG
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setReqMsg(String reqMsg) {
        this.reqMsg = reqMsg == null ? null : reqMsg.trim();
    }

    /**
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.REG_DT
     *
     * @param regDt the value for AIP_WORKSPACE.REG_DT
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.MOD_DT
     *
     * @param modDt the value for AIP_WORKSPACE.MOD_DT
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }
}