package com.nomad.data.agent.domain.dao.common;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table AIP_WORKSPACE
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 29 14:31:25 KST 2020
 */
public class AipWorkspaceKey {
    /**
     */
    private String wkspcId;

    /**
     */
    public String getWkspcId() {
        return wkspcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIP_WORKSPACE.WKSPC_ID
     *
     * @param wkspcId the value for AIP_WORKSPACE.WKSPC_ID
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    public void setWkspcId(String wkspcId) {
        this.wkspcId = wkspcId == null ? null : wkspcId.trim();
    }
}