package com.nomad.data.agent.domain.mappers.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.nomad.data.agent.domain.dao.common.AipAlgorithm;
import com.nomad.data.agent.domain.dao.common.AipAlgorithmExample;
import com.nomad.data.agent.domain.dao.common.AipAlgorithmKey;

public interface AipAlgorithmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    long countByExample(AipAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int deleteByExample(AipAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int deleteByPrimaryKey(AipAlgorithmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int insert(AipAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int insertSelective(AipAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    List<AipAlgorithm> selectByExampleWithRowbounds(AipAlgorithmExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    List<AipAlgorithm> selectByExample(AipAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    AipAlgorithm selectByPrimaryKey(AipAlgorithmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int updateByExampleSelective(@Param("record") AipAlgorithm record, @Param("example") AipAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int updateByExample(@Param("record") AipAlgorithm record, @Param("example") AipAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int updateByPrimaryKeySelective(AipAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_algorithm
     *
     * @mbg.generated Thu Oct 17 13:20:23 KST 2019
     */
    int updateByPrimaryKey(AipAlgorithm record);

}