package com.nomad.data.agent.domain.mappers.common;

import com.nomad.data.agent.domain.dao.common.AipDockerImage;
import com.nomad.data.agent.domain.dao.common.AipDockerImageExample;
import com.nomad.data.agent.domain.dao.common.AipDockerImageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AipDockerImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    long countByExample(AipDockerImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int deleteByExample(AipDockerImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int deleteByPrimaryKey(AipDockerImageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int insert(AipDockerImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int insertSelective(AipDockerImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    List<AipDockerImage> selectByExampleWithRowbounds(AipDockerImageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    List<AipDockerImage> selectByExample(AipDockerImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    AipDockerImage selectByPrimaryKey(AipDockerImageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int updateByExampleSelective(@Param("record") AipDockerImage record, @Param("example") AipDockerImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int updateByExample(@Param("record") AipDockerImage record, @Param("example") AipDockerImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int updateByPrimaryKeySelective(AipDockerImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DOCKER_IMAGE
     *
     * @mbg.generated Wed Apr 22 17:39:33 KST 2020
     */
    int updateByPrimaryKey(AipDockerImage record);
}