package com.nomad.data.agent.domain.mappers.common;

import com.nomad.data.agent.domain.dao.common.AipDataSource;
import com.nomad.data.agent.domain.dao.common.AipDataSourceExample;
import com.nomad.data.agent.domain.dao.common.AipDataSourceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AipDataSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    long countByExample(AipDataSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int deleteByExample(AipDataSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int deleteByPrimaryKey(AipDataSourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int insert(AipDataSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int insertSelective(AipDataSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    List<AipDataSource> selectByExampleWithRowbounds(AipDataSourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    List<AipDataSource> selectByExample(AipDataSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    AipDataSource selectByPrimaryKey(AipDataSourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int updateByExampleSelective(@Param("record") AipDataSource record, @Param("example") AipDataSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int updateByExample(@Param("record") AipDataSource record, @Param("example") AipDataSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int updateByPrimaryKeySelective(AipDataSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_DATA_SOURCE
     *
     * @mbg.generated Thu Apr 09 16:00:16 KST 2020
     */
    int updateByPrimaryKey(AipDataSource record);
}