package com.nomad.data.agent.domain.mappers.common;

import com.nomad.data.agent.domain.dao.common.AipDataSetFileMap;
import com.nomad.data.agent.domain.dao.common.AipDataSetFileMapExample;
import com.nomad.data.agent.domain.dao.common.AipDataSetFileMapKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AipDataSetFileMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    long countByExample(AipDataSetFileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int deleteByExample(AipDataSetFileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int deleteByPrimaryKey(AipDataSetFileMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int insert(AipDataSetFileMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int insertSelective(AipDataSetFileMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    List<AipDataSetFileMap> selectByExampleWithRowbounds(AipDataSetFileMapExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    List<AipDataSetFileMap> selectByExample(AipDataSetFileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    AipDataSetFileMap selectByPrimaryKey(AipDataSetFileMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int updateByExampleSelective(@Param("record") AipDataSetFileMap record, @Param("example") AipDataSetFileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int updateByExample(@Param("record") AipDataSetFileMap record, @Param("example") AipDataSetFileMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int updateByPrimaryKeySelective(AipDataSetFileMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aip_data_set_file_map
     *
     * @mbg.generated Wed Apr 29 17:19:36 KST 2020
     */
    int updateByPrimaryKey(AipDataSetFileMap record);
}