package com.nomad.data.agent.domain.mappers.common;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.nomad.data.agent.domain.dao.common.AipLogs;
import com.nomad.data.agent.domain.dao.common.AipLogsExample;
import com.nomad.data.agent.domain.dao.common.AipLogsKey;

public interface AipLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    long countByExample(AipLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int deleteByExample(AipLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int deleteByPrimaryKey(AipLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int insert(AipLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int insertSelective(AipLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    List<AipLogs> selectByExampleWithRowbounds(AipLogsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    List<AipLogs> selectByExample(AipLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    AipLogs selectByPrimaryKey(AipLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByExampleSelective(@Param("record") AipLogs record, @Param("example") AipLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByExample(@Param("record") AipLogs record, @Param("example") AipLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByPrimaryKeySelective(AipLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_LOGS
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByPrimaryKey(AipLogs record);
}