package com.nomad.data.agent.domain.mappers.common;

import com.nomad.data.agent.domain.dao.common.AipServer;
import com.nomad.data.agent.domain.dao.common.AipServerExample;
import com.nomad.data.agent.domain.dao.common.AipServerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AipServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    long countByExample(AipServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int deleteByExample(AipServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int deleteByPrimaryKey(AipServerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int insert(AipServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int insertSelective(AipServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    List<AipServer> selectByExampleWithRowbounds(AipServerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    List<AipServer> selectByExample(AipServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    AipServer selectByPrimaryKey(AipServerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int updateByExampleSelective(@Param("record") AipServer record, @Param("example") AipServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int updateByExample(@Param("record") AipServer record, @Param("example") AipServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int updateByPrimaryKeySelective(AipServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_SERVER
     *
     * @mbg.generated Tue Apr 14 15:21:16 KST 2020
     */
    int updateByPrimaryKey(AipServer record);
}