package com.nomad.data.agent.domain.mappers.common;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.nomad.data.agent.domain.dao.common.AipUser;
import com.nomad.data.agent.domain.dao.common.AipUserExample;
import com.nomad.data.agent.domain.dao.common.AipUserKey;

public interface AipUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    long countByExample(AipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int deleteByExample(AipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int deleteByPrimaryKey(AipUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int insert(AipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int insertSelective(AipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    List<AipUser> selectByExampleWithRowbounds(AipUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    List<AipUser> selectByExample(AipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    AipUser selectByPrimaryKey(AipUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByExampleSelective(@Param("record") AipUser record, @Param("example") AipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByExample(@Param("record") AipUser record, @Param("example") AipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByPrimaryKeySelective(AipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_USER
     *
     * @mbg.generated Thu Apr 09 11:36:59 KST 2020
     */
    int updateByPrimaryKey(AipUser record);
}