package com.nomad.data.agent.domain.mappers.common;

import com.nomad.data.agent.domain.dao.common.AipWorkspace;
import com.nomad.data.agent.domain.dao.common.AipWorkspaceExample;
import com.nomad.data.agent.domain.dao.common.AipWorkspaceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AipWorkspaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    long countByExample(AipWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int deleteByExample(AipWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int deleteByPrimaryKey(AipWorkspaceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int insert(AipWorkspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int insertSelective(AipWorkspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    List<AipWorkspace> selectByExampleWithRowbounds(AipWorkspaceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    List<AipWorkspace> selectByExample(AipWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    AipWorkspace selectByPrimaryKey(AipWorkspaceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int updateByExampleSelective(@Param("record") AipWorkspace record, @Param("example") AipWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int updateByExample(@Param("record") AipWorkspace record, @Param("example") AipWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int updateByPrimaryKeySelective(AipWorkspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIP_WORKSPACE
     *
     * @mbg.generated Wed Apr 29 14:31:25 KST 2020
     */
    int updateByPrimaryKey(AipWorkspace record);
}